<?php
	
?>
<!DOCTYPE HTML>
<!--
	Overflow 1.0 by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	    <title>GAPAï - Interprétations proverbiales</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	    <meta name="generator" content="Google Web Designer 1.0.0.924">
		<meta name="Description" CONTENT="Appareil de capture sémantique pour l'interprétation de proverbes par des cartographies sémantiques"/>
		<meta name="Keywords" CONTENT="proverbe interprétation cartographie appareil capture sémantique"/>
		<meta name="Author" CONTENT="Samuel Szoniecky"/>
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic" rel="stylesheet" type="text/css" />
		<script src="js/jquery.min.js"></script>
		<script src="js/gapaii/jquery.poptrox-2.2.js"></script>
		<script src="js/gapaii/skel.min.js"></script>
		<script src="js/gapaii/init.js"></script>
		<script src="js/gapaii/gapaii.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/gapaii/skel-noscript.css" />
			<link rel="stylesheet" href="css/gapaii/style.css" />
		</noscript>
		<script type="text/javascript">
			var idBase="<?php echo $this->idBase; ?>";
			var idUti=-1;				
		    var urlGen = "http://localhost/generateur/services/api.php?oeu=6";
	        function load(idDiv, idCpt) {
	            d3.text(urlGen+"&cpt="+idCpt, function(fragment) {
	                d3.select("#"+idDiv).html(fragment);
	            });
	        }
	    </script>
	</head>
	<body>

		<!-- Header -->
			<section id="header">
				<header>
					<h1>GAPAII</h1>
					<p>Interprétations Proverbiales</p>
				</header>
				<footer>
					<a href="#first" class="button style2 scrolly">Inscription</a>
					<a href="#second" class="button style2 scrolly">Connexion</a>
				</footer>
			</section>
		<!-- Feature 1 -->
			<article id="first" class="container box style1 right">
				<a href="http://ineedchemicalx.deviantart.com/art/Time-goes-by-too-fast-335982438" class="image full"><img src="img/gapaii/pic01.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Inscription</h2>
					</header>
					<form id="inscription" name="inscription" enctype="application/x-www-form-urlencoded" action="<?php echo WEB_ROOT;?>/public/auth/inscription" method="post">
						<div class="row half">
							<input type="hidden" id="ajax" name="ajax" value="true" />
							<input type="hidden" name="idBase" value="<?php echo $this->idBase; ?>" />
							<div class="6u"><input type="text" class="text" id="login" name="login" value="" placeholder="Login" /></div>
							<div class="6u"><input type="password" class="text" id="mdp" name="mdp" value="" placeholder="Mot de passe" /></div>
						</div>
						<div class="row half">
							<div class="12u">
								<input type="text" class="text" id="email" name="email" value="" placeholder="Email" />
							</div>
						</div>
						
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><input type="submit" class="button form" name="envoyer" id="boutonenvoyer" value="envoyer"></li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</article>
		
		<!-- Feature 2 -->
			<article id="second" class="container box style1 left">
				<a href="http://ineedchemicalx.deviantart.com/art/Time-goes-by-too-fast-335982438" class="image full"><img src="img/gapaii/pic01.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Connexion</h2>
					</header>
					<form id="connexion" name="connexion" enctype="application/x-www-form-urlencoded" action="<?php echo WEB_ROOT;?>/public/auth/login" method="post">
						<div class="row half">
							<input type="hidden" name="ajax" value="true" />
							<input type="hidden" name="idBase" value="<?php echo $this->idBase; ?>" />
							<div class="6u"><input type="text" class="text" name="login" value="" placeholder="Login" /></div>
							<div class="6u"><input type="password" class="text" name="password" value="" placeholder="Mot de passe" /></div>
						</div>
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><input type="submit" class="button form" name="submit" id="submit" value="Connexion"></li>
								</ul>
							</div>
						</div>
					</form>					
				</div>
			</article>

		<!-- Feature 2 -->
			<article class="container box style1 left">
				<a href="http://ineedchemicalx.deviantart.com/art/Kingdom-of-the-Wind-348268044" class="image full"><img src="img/gapaii/pic02.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Proverbes</h2>
					</header>
					<p id="genPro"></p>
					<input type="submit" class="button form" name="submit" id="submit" value="Génère">
				</div>
			</article>
		
		<!-- Portfolio -->
			<article class="container box style2">
				<header>
					<h2>Partenaires du projet</h2>
					<p></p>
				</header>
				<div class="inner gallery">
					<div class="row flush">
						<div class="3u"><a href="img/gapaii/fulls/02.jpg" class="image full"><img src="img/logoArtsH2H.png" alt="" title="LABEX ARTS H2H" /></a></div>
						<div class="3u"><a href="http://www.paragraphe.info" class="image full"><img src="img/logo_paragraphe.gif" alt="" title="Laboratoire Paragraphe" /></a></div>
						<div class="3u"><a href="img/gapaii/fulls/03.jpg" class="image full"><img src="img/logoDIPRALANG.png" alt="" title="Laboratoire DIPRALANG" /></a></div>
						<div class="3u"><a href="img/gapaii/fulls/04.jpg" class="image full"><img src="img/logoUMR7023.png" alt="" title="Laboratoire" /></a></div>
					</div>
				</div>
			</article>
		
		<!-- Contact -->
			<article class="container box style3">
				<header>
					<h2>Nisl sed ultricies</h2>
					<p>Diam dignissim lectus eu ornare volutpat orci.</p>
				</header>
				<form>
					<div class="row half">
						<div class="6u"><input type="text" class="text" name="name" placeholder="Name" /></div>
						<div class="6u"><input type="text" class="text" name="email" placeholder="Email" /></div>
					</div>
					<div class="row half">
						<div class="12u">
							<textarea name="message" placeholder="Message"></textarea>
						</div>
					</div>
					<div class="row">
						<div class="12u">
							<ul class="actions">
								<li><a href="#" class="button form">Send Message</a></li>
							</ul>
						</div>
					</div>
				</form>
			</article>
		
		<!-- Generic -->
		<!--
			<article class="container box style3">
				<header>
					<h2>Generic Box</h2>
					<p>Just a generic box. Nothing to see here.</p>
				</header>
				<section>
					<header>
						<h3>Paragraph</h3>
						<p>This is a byline</p>
					</header>
					<p>Phasellus nisl nisl, varius id <sup>porttitor sed pellentesque</sup> ac orci. Pellentesque 
					habitant <strong>strong</strong> tristique <b>bold</b> et netus <i>italic</i> malesuada <em>emphasized</em> ac turpis egestas. Morbi 
					leo suscipit ut. Praesent <sub>id turpis vitae</sub> turpis pretium ultricies. Vestibulum sit 
					amet risus elit.</p>
				</section>
				<section>
					<header>
						<h3>Blockquote</h3>
					</header>
					<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget.
					tempus euismod. Vestibulum ante ipsum primis in faucibus.</blockquote>
				</section>
				<section>
					<header>
						<h3>Divider</h3>
					</header>
					<p>Donec consectetur <a href="#">vestibulum dolor et pulvinar</a>. Etiam vel felis enim, at viverra 
					ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel. Praesent nec orci 
					facilisis leo magna. Cras sit amet urna eros, id egestas urna. Quisque aliquam 
					tempus euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
					posuere cubilia.</p>
					<hr />
					<p>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra 
					ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel. Praesent nec orci 
					facilisis leo magna. Cras sit amet urna eros, id egestas urna. Quisque aliquam 
					tempus euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
					posuere cubilia.</p>
				</section>
				<section>
					<header>
						<h3>Unordered List</h3>
					</header>
					<ul class="default">
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
					</ul>
				</section>
				<section>
					<header>
						<h3>Ordered List</h3>
					</header>
					<ol class="default">
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
						<li>Donec consectetur vestibulum dolor et pulvinar. Etiam vel felis enim, at viverra ligula. Ut porttitor sagittis lorem, quis eleifend nisi ornare vel.</li>
					</ol>
				</section>
				<section>
					<header>
						<h3>Table</h3>
					</header>
					<div class="table-wrapper">
						<table class="default">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Description</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>45815</td>
									<td>Something</td>
									<td>Ut porttitor sagittis lorem quis nisi ornare.</td>
									<td>29.99</td>
								</tr>
								<tr>
									<td>24524</td>
									<td>Nothing</td>
									<td>Ut porttitor sagittis lorem quis nisi ornare.</td>
									<td>19.99</td>
								</tr>
								<tr>
									<td>45815</td>
									<td>Something</td>
									<td>Ut porttitor sagittis lorem quis nisi ornare.</td>
									<td>29.99</td>
								</tr>
								<tr>
									<td>24524</td>
									<td>Nothing</td>
									<td>Ut porttitor sagittis lorem quis nisi ornare.</td>
									<td>19.99</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<td colspan="3"></td>
									<td>100.00</td>
								</tr>
							</tfoot>
						</table>
					</div>
				</section>
				<section>
					<header>
						<h3>Form</h3>
					</header>
					<form method="post" action="#">
						<div class="row">
							<div class="6u">
								<input class="text" type="text" name="name" id="name" value="" placeholder="John Doe" />
							</div>
							<div class="6u">
								<input class="text" type="text" name="email" id="email" value="" placeholder="johndoe@domain.tld" />
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<select name="department" id="department">
									<option value="">Choose a department</option>
									<option value="1">Manufacturing</option>
									<option value="2">Administration</option>
									<option value="3">Support</option>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<input class="text" type="text" name="subject" id="subject" value="" placeholder="Enter your subject" />
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<textarea name="message" id="message" placeholder="Enter your message"></textarea>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><a href="#" class="button form">Submit</a></li>
									<li><a href="#" class="button style3 form-reset">Clear Form</a></li>
								</ul>
							</div>
						</div>
					</form>
				</section>
			</article>
		-->
		
		<section id="footer">
			<ul class="icons">
				<li><a href="#" class="icon icon-twitter solo"><span>Twitter</span></a></li>
				<li><a href="#" class="icon icon-facebook solo"><span>Facebook</span></a></li>
				<li><a href="#" class="icon icon-google-plus solo"><span>Google+</span></a></li>
				<li><a href="#" class="icon icon-pinterest solo"><span>Pinterest</span></a></li>
				<li><a href="#" class="icon icon-dribbble solo"><span>Dribbble</span></a></li>
				<li><a href="#" class="icon icon-linkedin solo"><span>LinkedIn</span></a></li>
			</ul>
			<div class="copyright">
				<ul class="menu">
					<li>&copy; Untitled. All rights reserved.</li>
					<li>Design: <a href="http://html5up.net/">HTML5 UP</a></li>
					<li>Demo Images: <a href="http://ineedchemicalx.deviantart.com">Felicia Simion</a></li>
				</ul>
			</div>
		</section>

	</body>
</html>