<!DOCTYPE html>
<html>
<head>
    <title>W2UI Demo: sidebar-9</title>
    <link rel="stylesheet" type="text/css" href="../css/w2ui-dark.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="../js/w2ui.js"></script>
</head>
<body>

<div id="sidebar" style="height: 300px; width: 200px; float: left"></div>
<div style="margin-left: 220px;">
    <button class="w2ui-btn" onclick="w2ui.sidebar.goFlat()">Go Flat</button>
</div>
<div style="clear: both"></div>

<script type="text/javascript">
$(function () {
    $('#sidebar').w2sidebar({
        name : 'sidebar',
        flatButton: true,
        nodes: [
            { id: 'level-1', text: 'Level 1', img: 'icon-folder', expanded: true, group: true, groupShowHide: false,
              nodes: [ { id: 'level-1-1', text: 'Level 1.1', icon: 'fa-home' },
                       { id: 'level-1-2', text: 'Level 1.2', icon: 'fa-coffee' },
                       { id: 'level-1-3', text: 'Level 1.3', icon: 'fa-comment-alt' }
                     ]
            },
            { id: 'level-2', text: 'Level 2', img: 'icon-folder', group: true,
              nodes: [ { id: 'level-2-1', text: 'Level 2.1', icon: 'fa-star-empty' },
                       { id: 'level-2-2', text: 'Level 2.2', icon: 'fa-star-empty' },
                       { id: 'level-2-3', text: 'Level 2.3', icon: 'fa-star-empty' }
                     ]
            }
        ],
        onFlat: function (event) {
            $('#sidebar').css('width', (event.goFlat ? '35px' : '200px'));
        }
    });
});
</script>

</body>
</html>