<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	    <title>Planning - Tableau de bord</title>
	    <link rel="stylesheet" type="text/css" href="../css/w2ui-dark.css" />
	    <link rel="stylesheet" type="text/css" href="../font/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			//pour la gestion des vues ajax
			var urlP = "";
			var fctInit = false;
			var rsCalendar = <?php echo  json_encode($this->plannings); ?>;
			
			
			var rsInter, idxInter, rsCour, idxCour, rsPromo, idxPromo, rsEtu, idxEtu;
		</script>		
		<script type="text/javascript" src="../js/d3.js"></script>
	    <script type="text/javascript" src="../js/jquery.min.js"></script>
	    <script type="text/javascript" src="../js/w2ui.js"></script>

		<script type="text/javascript">
			//pur la gestion des vues ajax
			function init() {
			};		
		</script>	
		<style type="text/css">
			html, body {
			   width: 100%;
			   height: 100%;
			   background-color: black;
			}
			.trombi{
			    margin-bottom:76px;
			    display:inline-block;
			    border-collapse: collapse;
			    border-spacing: 0px;
			   width: 100%;
			   height: 100%;			    
			}
			.etu_tof {
			    padding:4px 5px;
			    vertical-align:bottom;
			    float:left;
			}
		</style>	
	</head>
	<body onload="init()">
	
		<div id="layoutMain" style="width: 100%; height: 800px;"></div>
		
		<script type="text/javascript">
		var topSize = 104;
		var googleProfileJDC = '<div class="g-page" data-width="319" data-href="//plus.google.com/u/0/101516073653937821733" data-theme="dark" data-layout="landscape" data-rel="publisher"></div>';
		var googleProfileUser = '<div class="g-person" data-href="https://plus.google.com/<?php echo $this->UserInfos["id"];?>" data-theme="dark" data-layout="landscape" data-rel="author"></div>';
	    var config = {
			    layoutMain: {
			        name: 'layoutMain',
			        padding: 4,
			        panels: [
			            { type: 'top', size: topSize, resizable: false
				        , content: '<div style="float:left;width:319px;">'
			            +googleProfileJDC
			            +'</div>'
			            +'<div id="toolbar" style="padding: 4px; border: 1px solid silver; border-radius: 3px"></div>'
			            },
			            { type: 'left', size: 200, resizable: true, content: 'Veuillez sélectionner un diplôme' },
			            { type: 'main', resizable: true, content: '', size:'100%'  },
			            { type: 'right', size: 200, resizable: true, content: '<?php echo json_encode($this->UserInfos); ?>' },
			            { type: 'bottom', size: 50, resizable: false, content: '' }
			       	]
			    },
			    tbMain : {
				    name: 'tbMain',
				    items: [
			            { type: 'menu',   id: 'mnuD', caption: 'Diplômes', icon: 'fa-university'
				            , items: rsCalendar},
				        { type: 'break',  id: 'break' },
				        { type: 'menu',  id: 'mnuPromo', caption: 'Promotions', icon:'fa-calendar', hidden:true
				            , items: rsPromo},
				        { type: 'break',  id: 'break0' },
			            { type: 'menu',   id: 'mnuI', caption: 'Intervenants', icon:'fa-group', hidden:true
				            , items: rsInter},
				        { type: 'break',  id: 'break0' },
			            { type: 'menu',   id: 'mnuC', caption: 'Cours', icon:'fa-book', hidden:true
				            , items: rsCour},
				        { type: 'break',  id: 'break1' },
				        { type: 'button',  id: 'tbCour', caption: 'Cours', icon:'fa-language', hidden:true},
				        { type: 'break',  id: 'break2' },
				        { type: 'button',  id: 'tbStat', caption: 'Statistiques', icon:'fa-language', hidden:true}, 
				        { type: 'break',  id: 'break3' },
				        { type: 'spacer' },
				        { type: 'button',  id: 'actu',  caption: 'actualiser', icon: 'fa-refresh' },
				        { type: 'break',  id: 'break4' },
				        { type: 'button',  id: 'utiSignOut',  caption: 'déconnexion', icon: 'fa-sign-out' },
				        { type: 'html',  id: 'mnuGoogleProfile',
			                html: ''+
			                      '<?php echo $this->UserInfos['name'];?> '+
			                      '<img height="26"  src="<?php echo $this->UserInfos['picture'];?>"/>'+
			                      '' 
			            },				        
				    ],
		            onClick: function (event) {
		                if (event.target == 'utiSignOut') {
			                	document.location.href="..<?php  echo $this->redirect; ?>&logout=1";
		                }
		                if (event.target == 'actu') {
		                	document.location.href="../?cleanCache=1&url=/planning/ui";
		                }		                
		                if (event.target.substring(0, 4) == 'mnuD' && event.subItem) {
			                	//charge le calendrier
		                		getDataPlanning(event.subItem);
		                }
		                if (event.target.substring(0, 8)  == 'mnuPromo' && event.subItem) {
			                //lock le main
			                w2ui.layoutMain.lock('main', 'Veuillez patienter...', true);
			                //récupère les photos
			                var url = "../flux/google?type=album&userId="+event.subItem['album userid']+"&albumId="+event.subItem['album albumid'];
							d3.json(url, function(data) {
								rsEtu = data.feed.entry.map(function(e, i){									
									return {id:i, mini:e['media$group']['media$thumbnail'][0], medium:e['media$group']['media$thumbnail'][1], large:e['media$group']['media$thumbnail'][2]};
									});																
				                //récupère les compétences				                
				                url = "../flux/google?type=csv&gDocId="+event.subItem['compétences docid'];
								d3.csv(url, function(data1) {
									data1.forEach(function(d){
										d.photos = rsEtu[d.numPhoto];
									});
									rsEtu = data1;
									//affiche les photos
								    w2ui.layoutMain.content('main', '<div id="tofs">'); 
								    getTrombi("#tofs", rsEtu);
								    w2ui.layoutMain.unlock('main');
								    //affiche les menus
								    w2ui['tbMain'].show('mnuI');
								    w2ui['tbMain'].show('mnuC');
								   // w2ui['tbMain'].show('tbCour');
								   // w2ui['tbMain'].show('tbStat');	
								   //enlève le message de gauche
								    w2ui.layoutMain.content('left', ""); 
										    
								});								
							});
		                }
		            }
			    },
			    gridCalendrier: { 
			        name: 'gridCalendrier', 
					header: 'Calendrier',		
			        show: { 
						header			: false,		
			            toolbar			: false,
						toolbarReload   : false,
						toolbarColumns  : false,
			            	toolbarSearch   : false,
			            	toolbarAdd      : false,
			            	toolbarDelete   : false,
			            	toolbarSave		: false,
			        },
			        columnGroups: [
						{ caption: 'SEPTEMBRE', span: 6}
			        ],
			        columns: [         
			            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
			            { field: 'jour', caption: 'Date', size: '80px', sortable: true, resizable: true},
			            { field: 'nbHeure', caption: 'cours', size: '50px', sortable: true, resizable: true},
			            { field: 'nbHeureJury', caption: 'jury', size: '50px', sortable: true, resizable: true},
			            { field: 'nbHeureTuto', caption: 'tutorat', size: '50px', sortable: true, resizable: true},
			            { field: 'nbHeurePro', caption: 'contrat', size: '50px', sortable: true, resizable: true},
			            { field: 'nbHeureStage', caption: 'stage', size: '50px', sortable: true, resizable: true},
			        ],
			        toolbar: {
			            items: [
			                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
			            ],
			            onClick: function (event) {
			            }
			        }
			    }
	    }		
		$(function () {
					    
		   $('#layoutMain').w2layout(config.layoutMain);
		   $('#toolbar').w2toolbar(config.tbMain); 
		    //w2ui.layoutMain.content('top', $().w2toolbar(config.tbMain)); 
		    //w2ui.layoutMain.content('main', $().w2grid(config.gridCalendrier)); 		    

		});
		//url vers fichier non publié
		var urlCouTot = "../flux/google?type=csv&gDocId=1vXOt_DiLRVdBWF9qw-XiP_DTFgmmM9cuZSMMnZyA3qo";
		var urlIntTot = "../flux/google?type=csv&gDocId=1R_Drqn_lubZgjkmu3kHicDt9GMFhqm-J7RyTmJVNtJs";
		//url vers fichier publié
		var urlPromoTot = "../flux/google?type=csvOpen&gDocId=1vXOt_DiLRVdBWF9qw-XiP_DTFgmmM9cuZSMMnZyA3qo&gid=603261686";
		var gData, gDataCal, dataCour, idxCour, dataInt, idxInt;
		//var urlCou = {"L3 PRO CDNL":"../data/planning/CDNL14-15_cours.csv"};
		var urlCou = {
				"Master 2 THYP":urlCouTot
				,"Master 2 PTN":urlCouTot
				,"L3 PRO CDNL":urlCouTot
				,"Master 2 NET":"../flux/google?type=csv&gDocId=1gYZxHacQ-dy7mHpIKbxKlAu1YLTSs-4SrJEmoVdFolU"
				,"Master 1 CEN":urlCouTot
				,"Master 1 GSI":urlCouTot
				,"Master 2 GSI":urlCouTot
				,"Master 2 AVUN":urlCouTot
				,"Master 2 CEN":urlCouTot
				,"CreaTIC Hypermedia":urlCouTot
				};
		//var urlInt = {"L3 PRO CDNL":"../data/planning/CDNL14-15_intervenants.csv"};
		var urlInt = {
				"Master 2 THYP":urlIntTot
				,"Master 2 PTN":urlIntTot
				,"L3 PRO CDNL":urlIntTot
				,"Master 2 NET":"../flux/google?type=csv&gDocId=1fvVB3bDR74KnYgBhKJgttzqqwygfpuD_OaCu9zOgZ7A"
				,"Master 1 CEN":urlIntTot
				,"Master 1 GSI":urlIntTot
				,"Master 2 GSI":urlIntTot
				,"Master 2 AVUN":urlIntTot
				,"Master 2 CEN":urlIntTot
				,"CreaTIC Hypermedia":urlIntTot
				};
		var urlPromo = {
				"Master 2 THYP":""
				,"Master 2 PTN":""
				,"L3 PRO CDNL":urlPromoTot
				,"Master 2 NET":""
				,"Master 1 CEN":""
				,"Master 1 GSI":""
				,"Master 2 GSI":""
				,"Master 2 AVUN":""
				,"Master 2 CEN":""
				,"CreaTIC Hypermedia":""
				};
		
	    function getDataPlanning(sltPlan){
			if(urlCou[sltPlan.text] && urlInt[sltPlan.text]){	
                w2ui.layoutMain.lock('main', 'Veuillez patienter...', true);				
				var colIdxCour = 'New Apogée';
				//chargement des données de cours depuis les fichiers csv
				d3.csv(urlCou[sltPlan.text], function(data1) {
					rsCour = data1;
					//création de l'index des cours
					idxCour = [];
					rsCour.forEach(function(d) {
						idxCour.push(d[colIdxCour]);
						d.text = d[colIdxCour]+" "+d["Intitulés des EC"];
					});
					//rafraichi le menu
					var it = w2ui['tbMain'].get('mnuC');
					it.items = rsCour;
					w2ui['tbMain'].refresh('mnuC');
					//chargement des données d'intervenants
					d3.csv(urlInt[sltPlan.text], function(data3) {
						rsInter = data3;
						//création de l'index des intervenants
						idxInt = [];
						rsInter.forEach(function(d) {
							idxInt.push(d["Nom"]);
							d.text = d["Prénom"] +' '+  d["Nom"];
						});
						//rafraichi le menu
						var it = w2ui['tbMain'].get('mnuI');
						it.items = rsInter;
						w2ui['tbMain'].refresh('mnuI');

						//chargement des données de promotion
						if(urlPromo[sltPlan.text]){
							d3.csv(urlPromo[sltPlan.text], function(data4) {
								rsPromo = data4;								
								//création de l'index des promotions
								idxPromo = [];
								rsPromo.forEach(function(d) {
									idxPromo.push(d["anDeb"]+'-'+  d["anFin"]);
									d.text = d["anDeb"] +' - '+  d["anFin"];
								});
								//rafraichi le menu
								var it = w2ui['tbMain'].get('mnuPromo');
								it.items = rsPromo;
								w2ui['tbMain'].refresh('mnuPromo');

							});
						}						
						//creaPlanning(sltPlan.value);
					    w2ui.layoutMain.unlock('main');
					    w2ui['tbMain'].show('mnuPromo');
					    w2ui.layoutMain.content('left', "Veuillez sélectionner une promotion"); 
					    									
					});
				});
			}else{
				w2popup.open({
			        title: 'Erreur de données',
			        body: '<div class="w2ui-centered">Pas de données de cours pour ce planning</div>'
			    });
			}
		}


	    // Création du trombinoscope des étudiants
	    function getTrombi(id, rs){
	        var trombi = {};
	            
	        // create table for legend.
	        var table = d3.select(id).append("div").attr('class','trombi');
	        
	        // création d'un div et d'un svg par étudiants
	        var svg = table.selectAll("div")
	        	.data(rs).enter()
	        	.append("div")
	        	.attr("id",function(d,i){return "etu_"+i;})
	        	.attr("class","etu_tof")
				.append("svg")
		        	.attr("width", function(d){ return d.photos.large.width})
		        	.attr("height", function(d){ return d.photos.large.height})
	        // création de la photo
	        svg.append("image")
		            .attr("width", function(d){ return d.photos.large.width})
		            .attr("height", function(d){ return d.photos.large.height})
					.attr("xlink:href",function(d){ 
						return d.photos.large.url; 
						});
	        // création des infos de base
	        var dy = ".35em";
			var text = svg.append("text")
				.attr("dy", dy)
				.attr("class","textEtu")
				.text(function(d) {
					return d['Votre prénom']+" "+d['Votre nom'];
				})
				.attr("transform", "translate(10,10)")			
				.call(wrap, 100);
			//création des boutons de présences
	        svg.append("image")
	            .attr("width", "32")
	            .attr("height", "32")
	            .attr("x",32)
	            .attr("y",function(d){ return d.photos.large.height-32})
	            .on("click",setPresence(this))	     
	            .on("mouseover", function(d) {
			        d3.select(this).style("cursor", "pointer")
			      })
	            .on("mouseout", function(d) {
			        d3.select(this).style("cursor", "default")
			      })	                   
				.attr("xlink:href","../img/timeA.jpg");
	        svg.append("image")
	            .attr("width", "32")
	            .attr("height", "32")
	            .attr("x",64)
	            .attr("y",function(d){ return d.photos.large.height-32})
	            .on("click",setPresence(this))	     
	            .on("mouseover", function(d) {
			        d3.select(this).style("cursor", "pointer")
			      })
	            .on("mouseout", function(d) {
			        d3.select(this).style("cursor", "default")
			      })	                   
				.attr("xlink:href","../img/timeR.jpg");
	        svg.append("image")
	            .attr("width", "32")
	            .attr("height", "32")
	            .attr("x",96)
	            .attr("y",function(d){ return d.photos.large.height-32})
	            .on("click",setPresence(this))	     
	            .on("mouseover", function(d) {
			        d3.select(this).style("cursor", "pointer")
			      })
	            .on("mouseout", function(d) {
			        d3.select(this).style("cursor", "default")
			      })	                   
				.attr("xlink:href","../img/timeP.jpg");
			
			
				
			/*
				.text(null);
			text.append("tspan").attr("x", 0).attr("y", 0).attr("dy", dy)
				.text(function(d) {
					return d['Votre prénom']+" "+d['Votre nom'];
				});
			text.append("tspan").attr("x", 0).attr("y", 10).attr("dy", dy)
				.text(function(d) {
					return d['Votre mail'];
				});
			*/
	        return trombi;
	    }	   


		function wrap(text, width) {
			  text.each(function() {
			    var text = d3.select(this),
			        words = text.text().split(/\s+/).reverse(),
			        word,
			        line = [],
			        lineNumber = 0,
			        lineHeight = 0.8, // ems
			        y = text.attr("y"),
			        dy = parseFloat(text.attr("dy")),
			        tspan = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", dy + "em");
			    while (word = words.pop()) {
			      line.push(word);
			      tspan.text(line.join(" "));
			      if (tspan.node().getComputedTextLength() > width) {
			        line.pop();
			        tspan.text(line.join(" "));
			        line = [word];
			        tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", ((++lineNumber * lineHeight) + dy) + "em").text(word);
			      }
			    }
			  });
			}	    

		function setPresence(d){

			var deb = new Date();			
			var fin = ISODateString(new Date(deb.getTime() + 10*60000));		 
			var deb = ISODateString(deb);
			
			var dt = {'action':'insert','idCal':sltPlan.id
					,'params':{'summary':'','location':'','description':'','start':deb,'end':fin,'mail':''}};
			$.ajax({
	    		url: "events",
	    		data: dt,
	    		type: 'post',
	        	dataType: 'json',
	        	error: function(error){
	        		try {
	        			var js = JSON.parse(error.responseText);
	        		} catch (e) {
	        			console.log(error.responseText)            		  	
		      			w2alert("Erreur : "+e);
	        		}
	        	},            	
	        	success: function(result) {
        			console.log(result);            		  	
		        }
			});			
		}

		//merci à http://stackoverflow.com/questions/7244246/generate-an-rfc-3339-timestamp-similar-to-google-tasks-api
		function ISODateString(d){
			 function pad(n){return n<10 ? '0'+n : n}
			 return d.getUTCFullYear()+'-'
			      + pad(d.getUTCMonth()+1)+'-'
			      + pad(d.getUTCDate())+'T'
			      + pad(d.getUTCHours())+':'
			      + pad(d.getUTCMinutes())+':'
			      + pad(d.getUTCSeconds())+'Z'}

		</script>
	
		<!-- GOOGLE + profile 
		Placez cette balise dans l'en-tête ou juste avant la balise de fermeture du corps de texte. -->
		<script src="https://apis.google.com/js/platform.js" async defer>
		  {lang: 'fr'}
		</script>
	</body>
</html>