<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>catégorisation d'un flux d'image</title>
    <link rel="shortcut icon" href="../img/papi-sonar.ico">

    <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
    <script type="text/javascript" src="../js/d3.v5.min.js"></script>
    <script type="text/javascript" src="../js/jquery.min.js"></script>
    <script type="text/javascript" src="../js/site.js"></script>
    <script type="text/javascript" src="../js/polarclock.js"></script>
    <script type="text/javascript" src="../js/cartoaxes.js"></script>

    <script type="text/javascript" src="../font/font-awesome/all.min.js"></script>

    <link href="../css/carousel.css" rel="stylesheet">
    <link href="../css/sonar.css" rel="stylesheet">

    <link rel="manifest" href="../manifest/sonar-manifest.json">
  <script>
    if('serviceWorker' in navigator) {
      navigator.serviceWorker.register('../js/sonar-sw.js')
        .then(reg => console.log('Service Worker registered', reg))
        .catch(err => console.error('Service Worker **not** registered', err));
    }
    else {
      console.warn('Service Worker not supported in this browser');
    }    
  </script>



    <style>
        body {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .bg-dark {
            background-color: #000000 !important;
        }

        .logo {
            vertical-align: top;
            height: 40px;
        }

        @font-face {
            font-family: "Quantify";
            src: url("../fonts/quantify/Quantify.ttf");
        }

        .logoTxt {
            vertical-align: sub;
            font-family: "Quantify";
        }

        .container {
            font-size: small;
        }

        .modal-content {
            background-color: black;
        }
    </style>

</head>

<body id="dummybodyid">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">
                <img class='logo' src="../svg/logo-sonar.svg" alt="logo-sonar" />
                <span class='logoTxt'>FLUX IMAGES</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-home"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-user-edit"></i>
                            <span id='txtUti'></span>
                            <span id='btnConnexion'></span>
                        </a>
                    </li>
                </ul>
                <div class="dropdown-divider"></div>                
                <div class="form-inline mt-2 mt-md-0 mr-3">
                    <!--
                    <label id='lblSrcFlux' for="inSrcFlux">Source du flux IIIF&nbsp;<i
                            class="far fa-question-circle"></i>&nbsp;</label>
                    <input class="form-control mr-sm-2" type="text" id="inSrcFlux">
                    -->
                    <label for="optSrcFlux">Source du flux IIIF&nbsp;
                        <i class="far fa-question-circle"></i>&nbsp;</label>
                    <select class="form-control" id="optSrcFlux">
                    </select>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="ckAleaTaille">
                        <label class="form-check-label" for="ckAleaTaille">
                            Taille aléatoire
                        </label>
                    </div>
                    <label for="optListeCpt">Liste des concepts&nbsp;
                        <i id='btnAjoutConcepts' class="fas fa-plus-circle"></i>&nbsp;</label>
                    <select class="form-control" id="optListeCpt">
                    </select>
                    <!--
                    <label for="inListeConcept">Vos concepts séparés par une ,</label>
                    <input class="form-control mr-sm-2" type="text" id="inListeConcept" value="">
                    <label for="inNomListeConcept">Nom de votre liste de concepts</label>
                    <input class="form-control mr-sm-2" type="text" id="inNomListeConcept" value="">
                    -->
                    <button id='btnSrcFlux' class="btn btn-outline-success my-2 my-sm-0" type="submit">Charger</button>
                </div>
                <!--
                <div class="dropdown-divider"></div>
                <div class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Chercher" aria-label="Chercher">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Trouver</button>
                </div>
                -->
                <img src="../svg/logo-paragraphe-blanc.svg" alt="logo-paragraphe" style="height:40px;" />
                <i class="fab fa-creative-commons"></i>&nbsp;<i class="fab fa-creative-commons-zero"></i>
            </div>
        </nav>
    </header>

    <main role="main">

        <div id="carouselEvals" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators" id="car-ind">
            </ol>
            <div class="carousel-inner" id="car-inn">
            </div>

            <a class="carousel-control-prev" href="#carouselEvals" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselEvals" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <div class="container">

            <div class="row" id='cartoEval'>
                <svg>
                    <defs>
                        <linearGradient id="linear-gradient" y1="0.5" x2="1" y2="0.5" gradientUnits="objectBoundingBox">
                            <stop offset="0" stop-color="#54d6ff"></stop>
                            <stop offset="1" stop-color="#5fff84"></stop>
                        </linearGradient>
                        <linearGradient id="linear-gradient-2" x1="0.005" y1="0.585" x2="0.991" y2="0.585"
                            xlink:href="#linear-gradient">
                        </linearGradient>
                        <linearGradient id="center-gradient" x1="0.717" y1="1" x2="0" y2="1"
                            gradientUnits="objectBoundingBox">
                            <stop offset="0" stop-color="#5ffd8a"></stop>
                            <stop offset="0.65" stop-color="#58e6ce"></stop>
                            <stop offset="1" stop-color="#55daf2"></stop>
                        </linearGradient>
                        <linearGradient id="degraxeH" x1="0%" y1="0%" x2="100%" y2="0%">
                            <stop stop-color="rgb(173, 158, 253)" offset="0%"></stop>
                            <stop stop-color="rgb(252, 161, 205)" offset="100%"></stop>
                        </linearGradient>
                        <linearGradient id="degraxeV" x1="0%" y1="0%" x2="0%" y2="100%">
                            <stop stop-color="rgb(3, 246, 162)" offset="0%"></stop>
                            <stop stop-color="rgb(84, 214, 255)" offset="100%"></stop>
                        </linearGradient>
                    </defs>
                </svg>

            </div><!-- /.row -->

        </div><!-- /.container -->

        <!-- FOOTER -->
        <footer class="container">
        </footer>
    </main>


    <!-- Fenêtre modale pour le temps de chargement -->
    <div class="modal fade" id="modWait" tabindex="-1" role="dialog" aria-labelledby="modWaitLbl" aria-hidden="true">
        <div class="modal-dialog modal-full" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modWaitLbl">Merci de patienter...</h5>
                </div>
                <div class="modal-body" style="height: 180px;">
                    <div id="loader" style="display:block;"></div>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>


    <script src="../js/popper.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script>
        var idBase = '<?php echo $this->idBase; ?>',
            uti = <?php echo $this->uti; ?>,
            urlColIIIF = '<?php echo $this->urlColIIIF; ?>', lstIIIF=[],
            urlColCrible = '<?php echo $this->urlColCribles; ?>',lstCrible = [],
            urlItemCrible = '<?php echo $this->urlItemCribles; ?>',lstItemCrible = [],
            height = window.innerHeight,
            width = window.innerWidth,
            svg, pc, ca, tofEval, geo=false;
        prefUrl = '../';
        //récupère la géolocalisation de l'utilisateur
        if (navigator.geolocation) {
	        navigator.geolocation.getCurrentPosition(function(p){
                geo = p;
            });
	    }
                

        //gestion des événements
        d3.select('#btnSrcFlux')
            .on('click', function () {
                //showCartoHorlo();
                //let src = document.getElementById("inSrcFlux").value;
                let url = document.getElementById("optSrcFlux").value;                
                console.log('Charge les images du flux IIIF :' + url);
                if(url)showSource(url);
            });
        d3.select('#btnConnexion')
            .on('click', function () {
                if( d3.select('#txtUti').html)
                    deconnexion("sonar/diaporama");
                else
                    connexion("sonar/diaporama");
                //console.log("connexion ou déconnexion de l'utilisateur");
            });
        d3.select('#btnAjoutConcepts')
            .on('click', function () {
                console.log("ajoute une structure de concept");
            });
            
        //charges les données del'application
        showUti();
        getListeSource();
        getListeCrible();


        function showUti() {
            d3.select('#txtUti').html(uti.login);
            let btn = '<i class="fas fa-sign-in-alt"></i>';
            if (uti.uti_id != 1) btn = '<i class="fas fa-sign-in-alt"></i>';
            d3.select('#btnConnexion').html(btn);
        }

        function getListeSource() {

            //ajoute la liste des flux
            $.ajax({
                url: urlColIIIF,
                dataType: "json",
                method: "GET",
                error: function (error) {
                    console.log("Erreur : " + error.responseText);
                },
                success: function (data) {
                    console.log(data);
                    lstIIIF = data;
                    d3.select('#optSrcFlux').selectAll('option').data(lstIIIF).enter()
                        .append('option')
                        .attr('value', function (d, i) {
                            return d['dcterms:isReferencedBy'] ? d['dcterms:isReferencedBy'][0]['@id'] : false;})
                        .attr('idItem', function (d) {
                            return d['o:id'];})
                        .html(function (d) {
                            return d['dcterms:title'] ? d['dcterms:title'][0]['@value'] : 'inconnu';
                            });
                }
            });
        }

        function getListeCrible() {

            //ajoute la liste des flux
            $.ajax({
                url: urlColCrible,
                dataType: "json",
                method: "GET",
                error: function (error) {
                    console.log("Erreur : " + error.responseText);
                },
                success: function (data) {
                    console.log(data);
                    lstCrible = data;
                    //ajoute la liste des cribles
                    d3.select('#optListeCpt').selectAll('option').data(lstCrible).enter()
                        .append('option')
                        .attr('id', function (d, i) {
                            return 'omkId_'+d['o:id'];})
                        .attr('value', function (d, i) {
                            return d['o:id'];})
                        .html(function (d) {
                            return d['dcterms:title'] ? d['dcterms:title'][0]['@value'] : 'inconnu';});
                }
            });
        }

        function showSource(src) {
            $('.navbar-collapse').collapse('hide');
            $('#modWait').modal('show');
            //
            $.ajax({
                url: src,
                dataType: "json",
                method: "GET",
                error: function (error) {
                    console.log("Erreur : " + error.responseText);
                    $('#modWait').modal('hide');
                },
                success: function (data) {
                    console.log(data);
                    //ajoute les photo à la gallery
                    ajoutPhotosGallerie(data.manifests);
                    //ajoute la cartographie
                    if (!ca) showCartoHorlo(data['@id']);
                }
            });
        }

        function ajoutPhotosGallerie(tofs) {

            //mélange toutes les photos
            //tofEval = d3.shuffle(tofs);
            tofEval = tofs;

            // Remove old elements as needed.
            d3.select('#car-ind').selectAll('li').remove();
            d3.select('#car-inn').selectAll('div').remove();


            //Ajoute la photo à la gallerie
            var li = d3.select('#car-ind').selectAll('li')
                .data(tofEval).enter().append('li')
                .attr('data-target', "#carouselEvals")
                .attr('data-slide-to', function (d, i) {
                    return i;
                })
                .attr('class', function (d, i) {
                    if (i == 0) return 'active';
                });

            var items = d3.select('#car-inn').selectAll('div')
                .data(tofEval).enter().append('div')
                .style('max-height', height / 3 + "px")
                .attr('class', function (d, i) {
                    var c = 'carousel-item';
                    if (i == 0) c += ' active';
                    return c;
                });

            //code pour ajouter des images
            items.append('img')
                .attr('id', function (d, i) {
                    d.idImg = 'img_' + i;
                    return d.idImg;
                })
                .attr('class', 'd-block img-fluid')
                .style('max-height', height / 3 + "px");

            //code pour ajouter des svg
            items.append('svg')
                .attr('id', function (d, i) {
                    d.idSvg = 'svg_' + i;
                    return d.idSvg;
                })
                .style('width', "100%")
                .style('height', "100%")
                .append('rect')
                .attr('id', function (d, i) {
                    d.idRect = 'rect_' + i;
                    return d.idRect;
                })
                .style('width', '100%')
                .style('height', '100%')
                .style('position', 'absolute')
                .style('top', '0px')
                .style('fill-opacity', '0')
                .style('stroke-width', '4')
                .style('fill', 'none')
                .style('stroke', 'green');


            /*ajoute le descriptif
	    var block = items.append('div').attr('class', 'carousel-caption d-none d-md-block');
	    block.append('h3').text(function (d) {
	        return d.label;
	    });
	    block.append('h4').text(function (d) {
	        return d.idOmk;
	    });
	    block.append('p').append('a')
	        .attr('href', function (d) {
	            return d.original;
	        })
	        .attr('target', '_blank').text('original');
        */

            initCarousel();
        }

        function initCarousel() {

            //ajoute les événements
            $('#carouselEvals').on('slid.bs.carousel', function (e) {
                //
                if (!tofEval[e.to].infos) {
                    //$('.carousel').carousel('pause');                                
                    getTofIIIF(e.to);
                    $('#modWait').modal('hide');
                }else{
                    //récupère les data
                    ca.idDoc = tofEval[e.to].idDoc;
                    ca.drawData();                    
                }
                console.log(e);
                //$('.carousel').carousel('pause');                                
            })
            $('.carousel').carousel({
                interval: 5000
            })
            //$('.carousel').carousel();
            //$('.carousel').carousel('cycle');
            //$('.carousel').carousel(tofEval.length-1);		
            //$('.carousel').carousel('pause');                                

        }

        function getTofIIIF(num) {
            let d = tofEval[num];
            $.ajax({
                url: d['@id'],
                dataType: "json",
                method: "POST",
                error: function (error) {
                    console.log("getTofIIIF Erreur : " + error.responseText);
                },
                success: function (data) {
                    console.log(data);
                    d.infos = data;
                    let url = "";
                    //vérifie la présence de visage
                    d.infos.metadata.forEach(function (t) {
                        if (t.label == "faceAnnotations") {
                            url = getVisageTofIIIF(d, t);
                        }
                    })

                    //récupère l'image si pas de visage
                    if (url == "") {
                        let isAlea = document.getElementById("ckAleaTaille").checked;
                        url = getTailleTofIIIF(d,isAlea);
                    }

                    //code pour ajouter une image HTML
                    d3.select("#" + d.idImg).attr('src', url);

                    /*code pour une image SVG
                    d3.select("#"+d.idSvg).append('image')
                        .attr('class','iiif')
                        .attr('x',0)
                        .attr('y',0)
                        .attr('xlink:href',url);
                    */

                    //précise l'url à la carto
                    d.idDoc = url;
                    ca.idDoc = url;
                    //précise le json de la photo
                    ca.data = {
                        'IIIF':d.infos.sequences[0].canvases[0].images[0].resource.service["@id"]+'/info.json'
                        ,'title':d.infos.label
                    };


                    //affiche les données enregistrées
                    ca.drawData();                    

                }
            });

        }


        function getTailleTofIIIF(d, alea) {
            //item vient de IIIF
            //récupère la position et la taille du rectangle
            let bb = d3.select('#' + d.idRect).node().getBBox();

            //calcule l'url IIIF
            let zoom = 2,
                minPixel = 0,
                imgOmk = d.infos.sequences[0].canvases[0].images[0].resource.service["@id"],
                w = d.infos.sequences[0].canvases[0].width, h = d.infos.sequences[0].canvases[0].height, img = {};
                img.r = 0;
            if (!d.images) d.images = [];
            if(alea){
                img.w = parseInt(w < bb.width ? bb.width * zoom : bb.width / zoom);
                img.h = parseInt(h < bb.height ? bb.height * zoom : bb.height / zoom);
                img.x = parseInt(d3.randomUniform(minPixel, w > img.w ? w - img.w : w)());
                img.y = parseInt(d3.randomUniform(minPixel, h > img.h ? h - img.h : h)());
            }else{
                img.w = parseInt(w);
                img.h = parseInt(h);
                img.x = 0;
                img.y = 0;
            }
            //calcul la taille de représentation
//            let sclW = d3.scaleLinear().domain([0,img.w]).range([0,bb.width]);
//            let sclH = d3.scaleLinear().domain([0,img.h]).range([0,bb.height]);
            let diaW = bb.width;
            let diaH = bb.height;            
            let coef = img.h > img.w ? img.h / img.w : img.w / img.h;
            if(img.w > bb.width){
                diaW = bb.width - (bb.width/coef);
            }else if(img.h > bb.height){
                diaH = bb.height - (bb.height/coef);
            }

            //construction de l'url
            img.url = imgOmk + '/' + img.x + ',' + img.y + ',' + (img.w) + ',' + (img.h) + '/' 
                + parseInt(diaW) + ',' + parseInt(diaH) + '/' + img.r + '/default.jpg';
            console.log(img);
            d.images.push(img);

            return img.url;
        }

        function getVisageTofIIIF(d, t) {
            //item vient de IIIF
            //récupère la position et la taille du rectangle
            let bb = d3.select('#' + d.idRect).node().getBBox();

            //récupère a défitinition du visage
            let vs = JSON.parse('[' + t.value + ']');
            console.log(vs);

            let img, imgOmk = d.infos.sequences[0].canvases[0].images[0].resource.service["@id"];
            vs.forEach(function (v) {
                //calcule l'url IIIF        
                if (!d.images) d.images = [];
                img = {
                    'w': v.boundingPoly.vertices[1].x - v.boundingPoly.vertices[0].x,
                    'h': v.boundingPoly.vertices[2].y - v.boundingPoly.vertices[0].y,
                    'x': v.boundingPoly.vertices[0].x,
                    'y': v.boundingPoly.vertices[0].y,
                    'r': 0
                };
                img.url = imgOmk + '/' + img.x + ',' + img.y + ',' + (img.w) + ',' + (img.h) + '/' + parseInt(bb
                    .width) + ',' + parseInt(bb.height) + '/' + img.r + '/default.jpg';
                console.log(img);
                d.images.push(img);
            });
            return img.url;
        }

        function showCartoHorlo(id) {
            //récupère la taille du conteneur
            let c = document.getElementById('cartoEval');
            //calcul les tailles
            let spacing = 0.000001,
                w = width,
                h = height / 2, //w = c.clientWidth, h = c.clientHeight,        
                rayon = w < h ? w / 2 : h / 2;
            
            //suprime le composants existants
            d3.select(".cartoaxes").remove();
            d3.select(".polarclock").remove();

            svg = d3.select("#cartoEval svg")
                .attr("id", "svgGlobal")
                .attr("width", w)
                .attr("height", h);
            //ajoute la polar clock
            pc = new polarclock({
                'idSvg': 'svgGlobal',
                'spacing': spacing,
                'width': w,
                'height': h,
                'chrono': true,
                'nbCouche': 6
            });
            //récupère le crible
            //let stct = document.getElementById('inListeConcept').value;
            let idOmk = '#omkId_'+document.getElementById('optListeCpt').value; 
            let oOmk = d3.select(idOmk).data();
            let urlCpt = urlItemCrible+oOmk[0]["dcterms:title"][0]["@value"]; 
            
            $.ajax({
                url: urlCpt,
                dataType: "json",
                method: "GET",
                error: function (error) {
                    console.log("getConcept Erreur : " + error.responseText);
                },
                success: function (data) {
                    //ajoute la carto axe            
                    lstItemCrible = [];
                    var lbl,id,lblP,idP;
                    data.forEach(function(d){
                        lbl = d['skos:prefLabel'][0]['@value'];
                        id = d['o:id'];
                        lblP = d['skos:inScheme'][0]['display_title'];
                        idP = d['skos:inScheme'][0]['value_resource_id'];
                        lstItemCrible.push({'label':lbl,'id':id,'idP':idP,'labelP':lblP});
                    });
                    ca = new cartoaxes({
                        'idSvg': 'svgGlobal',
                        'tick': 0,
                        'idDoc': id,
                        'urlData':'../sonar/flux?q=getEvalsOmk',
                        'typeSrc':'IIIF',
                        'inScheme':lblP,
                        'crible': lstItemCrible,
                        'fctGetGrad': pc.getInstantColors,
                        'fctSavePosi': savePosi,
                        'width': w,
                        'height': h
                    });
                    //pc.toggleTimer();
                    pc.resetTimer()
                  

                }
            });

        }

        function savePosi(d) {
            let srcFlux = document.getElementById("optSrcFlux").value;
            let flux = lstIIIF.filter(function(f){
                return f['dcterms:isReferencedBy'][0]['@id']==srcFlux;
            })
            d.idFlux = flux[0]['o:id'];
            d.idCrible = document.getElementById("optListeCpt").value;
            let omk = {
                'dcterms:title':flux[0]["dcterms:title"][0]["@value"]+' _ '+d.infos.title+' : '+d.degrad.date
                ,'dcterms:isReferencedBy':d.infos.title+' : '+d.degrad.date+' : '+uti.login
                ,'dcterms:isPartOf':[{'type':'resource','value':d.idFlux}]
                ,'resource_class':"SemanticPosition"
                ,'ma:creationDate':d.degrad.date
                ,'ma:hasCreator':uti.login
                ,'ma:hasRating':[]
                ,'ma:isRatingOf':[]
                ,'ma:ratingScaleMax':ca.xMax
                ,'ma:ratingScaleMin':ca.xMin
                ,'ma:hasRatingSystem':[{'type':'resource','value':d.idCrible}]
                ,'ma:locationLatitude':geo.coords.latitude
                ,'ma:locationLongitude':geo.coords.longitude
                ,'ma:hasSource':d.id
                ,'ma:isFragmentOf':{'title':d.infos.title,'IIIF':d.infos.IIIF}
                ,'jdc:degradName':d.degrad.nom
                ,'jdc:degradColors':d.degrad.colors
                ,'jdc:hasDoc':d.id
                ,'jdc:distanceCenter':d.distance
                ,'jdc:hasConcept':[]
                ,'jdc:distanceConcept':[]
                ,'jdc:x':d.x
                ,'jdc:y':d.y
                ,'jdc:xRatingValue':d.numX
                ,'jdc:yRatingValue':d.numY
            }
            d.crible.forEach(function(c){
                omk['ma:hasRating'].push(c.p);
                omk['ma:isRatingOf'].push({'type':'resource','value':c.t.id});
                omk['jdc:hasConcept'].push({'type':'resource','value':c.t.id});
                omk['jdc:distanceConcept'].push(c.p);
            })
            //message pour patienter
            $('#modWait').modal('show');
            //carrousel en pause
            $('.carousel').carousel('pause');                                
            $.post('../sonar/flux', {
                    'q': 'savePosiOmk',
                    'type':'IIIF',
                    'dt': omk                    
                }, function (data) {
                    console.log(data);
                }, "json")
                .fail(function (e) {
                    throw new Error("Sauvegarde imposible : " + e);
                })
                .always(function () {
                    $('#modWait').modal('hide');
                });
        }
        $('.navbar-collapse').collapse('show');
    </script>
</body>

</html>