<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script type='text/javascript' src="../js/d3.v3.js"></script>
	<script type='text/javascript' src="../js/graine.js"></script>
	<script type='text/javascript' src="../js/branche.js"></script>
	<script type='text/javascript' src="../js/racine.js"></script>
	<script type='text/javascript' src="../js/bulle.js"></script>
	<style>	
		text {
		  font-size: 11px;
		  pointer-events: none;
		}
		
		text.parent {
		  fill: steelblue;
		}
		
		circle {
		  fill: #ccc;
		  stroke: #999;
		  pointer-events: all;
		}
		
		circle.parent {
		  fill: steelblue;
		  fill-opacity: .1;
		  stroke: steelblue;
		}
		
		circle.parent:hover {
		  stroke-width: .5px;
		}
		
		circle.child {
		  pointer-events: all;
		}

		path {
		  fill: #ccc;
		  stroke: #999;
		  pointer-events: all;
		}
		
		path.parent {
		  fill: steelblue;
		  fill-opacity: .1;
		  stroke: steelblue;
		}
		
		path.parent:hover {
		  stroke-width: .5px;
		}
		
		path.child {
		  pointer-events: none;
		}

		rect {
		  stroke: #eee;
		  fill: #aaa;
		  fill-opacity: .8;
		}
		
		rect.parent {
		  cursor: pointer;
		  fill: steelblue;
		}
		</style>
</head>
<body>
	<div id="chart"></div>
	<script type="text/javascript">
		var arrGrn = [];
		var arrBll = [];
		var arrBrc = [];
		var arrRcn = [];
       	var divElem2 = d3.select("#chart");

       	var svgBulle = divElem2.append("svg:svg")
            .attr("width", "300")
            .attr("height", "100%")
            .attr("id", "svgBulle")
            .append("svg:g");
		arrBll.push(new bulle({id:"bulle1", svg:svgBulle, r:300, urlJson:"../biblio/dewey", urlBookDetail:"../biblio/bookdetail?idsDoc="}));
        
       	var svgGraine = divElem2.append("svg:svg")
	        .attr("x", "300")
	        .attr("width", "300")
	        .attr("height", "100%")
	        .attr("id", "svgGraine")
	        .append("svg:g");               	
		//arrGrn.push(new graine({id:"grn1", svg:svgGraine, urlJson:"../biblio/utidetail?db=flux_zotero", r:6, x:10, y:10}));
		
       	var svgBranche = divElem2.append("svg:svg")
        .attr("x", "600")
        .attr("width", "600")
        .attr("height", "100%")
        .attr("id", "svgBranche")
        .append("svg:g");               	
		//arrBrc.push(new branche({id:"brc1", svg:svg, x:200, y:200, points:[{x:0, y:60},{x:50, y:110},{x:90, y:70},{x:140, y:100}]}));
                    
		//arrRcn.push(new racine({id:"rcn1", svg:svg, x:100, y:100, points:[{x:0, y:60},{x:50, y:110},{x:90, y:70},{x:140, y:100}]}));

	</script>	
  </body>
</html>	