<html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["treemap"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Location', 'Parent', 'Nombre', 'poids'],
          ['Global', null, 0, 0],
          ['Extraction total doc','Global',0, 0],
          ['Extraction total acteur','Global',0,0],
          ['Extraction total concept','Global',0,0],
          ['Extraction total lien','Global',0,0],
          ['Uniquement les bulletins doc','Extraction total doc',120139, 1],
          ['Uniquement les bulletins acteur','Extraction total acteur',1080, 2],
          ['Uniquement les bulletins concept','Extraction total concept',3123, 3],
          ['Uniquement les bulletins lien','Extraction total lien',200640, 4],
        ]);

        tree = new google.visualization.TreeMap(document.getElementById('chart_div'));

        tree.draw(data, {
          minColor: '#f00',
          midColor: '#ddd',
          maxColor: '#0d0',
          headerHeight: 15,
          fontColor: 'black',
          showScale: true
        });

      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
  </body>
</html>