<!DOCTYPE html>
<html>
<head>
<meta name="viewport"></meta>
<title>Comparaison des catégories</title>
<style type="text/css">

</style>
<script type="text/javascript">
	var prefUrl =  "../";
	var idBase = "flux_biolographes";

</script>
<script type="text/javascript" src="../js/d3.js"></script>
<script type="text/javascript" src="../js/jquery.min.js"></script>
<script type="text/javascript" src="../js/dimple.v2.1.0.min.js"></script>
<script type="text/javascript" src="../js/biolographes/modeles.js"></script>

<script type="text/javascript">

var svg, setAutoComplet = false;
d3.csv("../../data/biolographes/CatRapportsBiolLitt.csv", function(error, data) {
//d3.csv("../flux/google?type=css&gDocId=169QusRs3TyrqxzVb28hXX2E8FZsqWb01xIWpl5FDPns", function(error, data) {
	
	//construction des données	
	dtOrigine = data;
	csvGetCat("oui");
	
	//construction du graphique
	svg = dimple.newSvg("#viz", 1200, 3000);
	var myChart = new dimple.chart(svg, dtGraph);
    myChart.setBounds(400, 120, 800, 2700)
    myChart.addCategoryAxis("x", ["Auteur"]);
    var s = myChart.addCategoryAxis("y", ["Propriété"]);
    s.addOrderRule("Catégorie");
    myChart.addSeries("Catégorie", dimple.plot.bar);
    myChart.addLegend(0, 10, 1000, 60, "right");
    myChart.draw();
});	
</script>
</head>

<body>
  <div id="viz"></div>
</body>
</html>