<div id="form" style="width: 750px;">
    <div class="w2ui-page page-0">
        <div style="width: 340px; float: left; margin-right: 0px;">
            <div style="padding: 3px; font-weight: bold; color: #777;">General</div>
            <div class="w2ui-group" style="height: 185px;">
                <div class="w2ui-field w2ui-span4">
                    <label>First Name:</label>
                    <div>
                        <input name="first_name" type="text" maxlength="100" style="width: 100%">
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>Last Name:</label>
                    <div>
                        <input name="last_name" type="text" maxlength="100" style="width: 100%">
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>Comments:</label>
                    <div>
                        <textarea name="comments" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div style="width: 380px; float: right; margin-left: 0px;">
            <div style="padding: 3px; font-weight: bold; color: #777;">Address</div>
            <div class="w2ui-group" style="height: 185px;">
                <div class="w2ui-field w2ui-span4">
                    <label>Address:</label>
                    <div>
                        <input name="address1" type="text" maxlength="100" style="width: 100%"/>
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>Line 2:</label>
                    <div>
                        <input name="address2" type="text" maxlength="100" style="width: 100%"/>
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>City:</label>
                    <div>
                        <input name="city" type="text" maxlength="50" size="25"/>
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>State:</label>
                    <div>
                        <input name="state" type="text" maxlength="2" size="2"/>
                    </div>
                </div>
                <div class="w2ui-field w2ui-span4">
                    <label>Zip:</label>
                    <div>
                        <input name="zip" type="text" maxlength="10" size="10"/>
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both; padding-top: 15px;">
            <div style="padding: 3px; font-weight: bold; color: #777;">Additional Fields</div>
            <div class="w2ui-group">
                <div class="w2ui-field">
                    <label>Short Bio:</label>
                    <div>
                        <textarea name="short_bio" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
                    </div>
                </div>
                <div class="w2ui-field">
                    <label>Talk Name:</label>
                    <div>
                        <input name="talk_name" type="text" maxlength="100" style="width: 100%"/>
                    </div>
                </div>
                <div class="w2ui-field">
                    <label>Talk Description:</label>
                    <div>
                        <textarea name="description" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>