<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8" />
			<title>Jardin des connaissances : connexion</title>
	        <link rel="stylesheet" type="text/css" href="../css/w2ui-dark.css" />
    			<script src="../js/jquery.min.js"></script>
    		    <script src="../js/w2ui-1.5.rc1.min.js"></script>
        
    			<style>
    			body{
    			 background-color:black;
    			 }
			#main {
				width:400px;
				height:630px;
				position:absolute;
				left:50%;
				top:50%;
				margin:-250px 0 0 -200px;
			}
            .btnAut {
                cursor:pointer;
                height:50px;
            }
            .divAut {    			
                padding:3px 3px;
                background-color:white;
                margin-right:10px;
			}
            </style>
		</head>
		<body >
			<div id="main"></div>
			<script type="text/javascript">
			var codeErreur = '<?php echo $this->code;?>';
			$(function () {
			    var pstyle = "border: 1px solid #dfdfdf; padding: 5px;";
			    $("#main").w2layout({
			        name: "layout",
			        panels: [
			            { type: "top", size: 50, style: pstyle, content: "<?php echo $this->erreur;?>" },
			            { type: "main", size: "50%", style: pstyle},
			            { type: "bottom", size: "50%", style: pstyle}
			            ]
			    });
			    	w2ui["layout"].content("main",$().w2form({ 
			        name     : "formLog",
			        url      : "login",
			        header   : "Jardin des connaissances<br/>choisissez une authentification",
                    toolbar: {
                            name : "tbFormLog",
                                items: [
                                    { type: "html",  id: "P8",
                                        html: function (item) {
                                            var html =
                                              "<div onclick='showP8Auth()' class=\'divAut\' >"+
                                              "<img src=\'../img/logop8-3.jpg\' class=\'btnAut\' alt=\'connexion Paris 8\' />"+
                                              "</div>";
                                            return html;
                                        }
                                    },
                                    { type: "html",  id: "aideTB",
                                        html: function (item) {
                                            var html =
                                                "<div onclick='showJDCAuth()' class=\'divAut\' >"+
                                                "<img src=\'../img/logo-jdc.png\' class=\'btnAut\' alt=\'connexion JDC\' />"+
                                                "</div>";
                                            return html;
                                        }
                                    },                                    
                                    { type: "html",  id: "google",
                                        html: function (item) {
                                            var html =
                                              "<div onclick='showGoogleAuth()' class=\'divAut\' >"+
                                              "<img src=\'../img/google.png\' class=\'btnAut\' alt=\'connexion Google\' />"+
                                              "</div>";
                                            return html;
                                        }
                                    },
                                ],
                                onClick: function (event) {
                                    if (event.target == "P8") console.log(event);
                                    if (event.target == "Google") console.log(event);
                                }
                            },
			        fields: [
			            { field: "l", html: { caption: 'login'}, hidden:true,  type: "text", required: true },
			            { field: "m", html: { caption: 'mot de passe'}, hidden:true,  type: "password", required: true }
			        ],
			        actions: {
			            connexion: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                window.location.assign("login?login="+this.record.l+"&mdp="+this.record.m+"&idBase=<?php echo $this->idBase;?>");
			            }
					},
			    		})
			    	);
			    	w2ui["layout"].content("bottom",$().w2form({ 
			        name     : "formIns",
			        header   : "Jardin des connaissances : inscription",
			        fields: [
			            { field: "login", type: "text", required: true },
			            { field: "mdp", html: { caption: 'mot de passe'}, type: "password", required: true },
			            { field: "email", type: "email", required: true }
			            ],
			        actions: {
			            inscription: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                var data = this.record;
                            data.idBase="<?php echo $this->idBase;?>";
			                data.ajax = 1;
							$.get("inscription",
								data,
					        		function(js){
					        			w2alert(js.message);
                                     if(codeErreur=="") window.location.assign("../"+js.redir);
					       		},"json");				                				                
			            }
					},
			    		})
					); 
				w2ui['layout'].toggle('bottom');
			});
			function showGoogleAuth(){
				var html = '<iframe src="google?idBase=<?php echo $this->idBase;?>&redir=<?php echo $this->redir;?>" style="width: 100%; height: 100%;">';
				w2popup.open({
			        title   : 'Authentification Google',
			        showMax : false,
			        body    : html,
			        onOpen  : function (event) {
			            event.onComplete = function () {
			            };
			        },
			    });	
			}
			function showJDCAuth(){
				w2ui["formLog"].fields[0].hidden = false;		
				w2ui["formLog"].fields[1].hidden = false;		
				w2ui["formLog"].render();
				w2ui['layout'].toggle('bottom');

			}
			function showP8Auth(){
				window.location.assign("cas?idBase=<?php echo $this->idBase;?>&redir=<?php echo $this->redir;?>");				
			}
			</script>
		  </body>
		</html>