<?php
	if($this->ajax){
		echo json_encode(array("message"=>$this->message, "redir"=>$this->redir, "rs"=>$this->rs));
	}else{
		$this->form->setAction($this->url());
		echo '<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8" />
			<title>Jardin des connaissances : inscription</title>
			<link rel="stylesheet" href="../css/site.css" />
		</head>
		<body>
			<h1>Le jardin des connaissances</h1>
			'.$this->form.'
		  </body>
		</html>	';	
	}
?>
