<?php
echo $this->urlBook;
echo $this->htmlBook;
print_r($this->arrBook);

// Title and Identifier are mandatory!
echo $this->arrBook["titre"]."<br/>";
echo $this->Identifier."<br/>";
echo $this->Langue."<br/>";
echo $this->arrBook["descriptif"]."<br/>";
echo $this->Auteur."<br/>";
echo $this->AuteurKey."<br/>";
echo $this->Editeur."<br/>";
echo $this->EditeurUrl."<br/>";
echo $this->Licence."<br/>";
echo $this->SourceURL."<br/>";

print_r($this->arrChap);

