<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>navigateur spatio temporel</title>

        <!-- Styles -->
        <link href="../css/leaflet.css" rel="stylesheet" type="text/css" />
        <link href="../css/jquery.slider.ithing.css" rel="stylesheet" type="text/css" />
        <link href="../css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="../css/spatiotempo/main.css" rel="stylesheet" type="text/css" />

        <!-- jQuery -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js" type="text/javascript"></script>
        <script src="../js/jquery.mousewheel.min.js" type="text/javascript"></script>
        <script src="../js/jquery.slider.min.js"></script>

        <!-- D3.js -->
        <script src="http://d3js.org/queue.v1.min.js" type="text/javascript"></script>
        <script src="http://d3js.org/topojson.v1.min.js" type="text/javascript"></script>
        <script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>

        <!-- Other libraries -->
        <script src="../js/knockout.min.js" type="text/javascript"></script>
        <script src="../js/crossfilter.min.js" type="text/javascript"></script>
        <script src="../js/leaflet.min.js"  type="text/javascript"></script>
        <script src="../js/moment.min.js"  type="text/javascript"></script>
        <script src="../js/moment.timezone.min.js"  type="text/javascript"></script>
        <script src="../js/bootstrap.min.js"></script>

        <!-- Main code -->
        <script src="../js/spatiotempo/main.js" type="text/javascript" charset="utf-8"></script>

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>

    <div class="container">

        <div id="map"></div>

        <div class="site-wrapper">

          <div class="site-wrapper-inner">

            <div class="cover-container">

              <div class="masthead clearfix">
                <div class="inner">
                    <div class="loading">
                        <h4>Loading data, please wait ...</h4>
                    </div>
                </div>
              </div>

              <div class="inner cover">

              </div>

              <div class="mastfoot">
                <div id="slider"></div>
                <div class="inner">
                  <p>Spatio temporal data visualizer using D3.js, Leaflet.js and Crossfilter by <a href="https://github.com/hugocore/spatiotemporal-visualizer">@hugocore</a></p>
                </div>
              </div>

            </div>

          </div>

        </div>

    </div>

    </body>
</html>
