<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Générateur</title>
    <link rel="stylesheet" type="text/css" href="../font/font-awesome/font-awesome.css" />
    <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../css/bootstrap-treeview.min.css" >
    <link rel="stylesheet" type="text/css" href="../css/w2ui-1.5.rc1.min.css" />
    <link rel="stylesheet" type="text/css" href="../css/font-awesome.css">

    <script type="text/javascript" src="../js/d3.v5.min.js"></script>
    <script type="text/javascript" src="../js/d3-array.v2.min.js"></script>    
    <script type="text/javascript" src="../js/jquery.min.js"></script>
	<script type="text/javascript" src="../js/popper.min.js"></script>
    <script type="text/javascript" src="../js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../js/bootstrap-treeview.js"></script>    
    <script type="text/javascript" src="../js/w2ui.min.js"></script>
  
    <style>

    </style>
  </head>
  <body>
    <div class="container-fluid" >
        <nav id="nbMain" class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <a class="navbar-brand" href="#">
                <h1 class="text-center" >Générateur - Gestion</h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="ddOeuvre" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Oeuvres</a>
                        <div id="ddOeuvreItem" class="dropdown-menu" aria-labelledby="ddOeuvre">
                            <a class="dropdown-item" href="#">Créer</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="ddUti" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Utilisateurs</a>
                        <div class="dropdown-menu" aria-labelledby="ddUti">
                            <a class="dropdown-item" href="#">Ajouter</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <button id="uti" class="btn btn-outline-success my-2 my-sm-0" type="button"><?php echo $this->login; ?></button>
                    <button class="btn btn-outline-danger my-2 my-sm-0" onclick="deconnexion()" type="button">déconnexion</button>
                </form>
            </div>
        </nav>	

        <div class="row">
            <div class="col-12">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="dico-tab" data-toggle="tab" href="#dico" role="tab" aria-controls="dico" aria-selected="true">Dictionnaires</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" id="etudiant-tab" data-toggle="tab" href="#etudiant" role="tab" aria-controls="etudiant" aria-selected="true">Etudiants</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" id="planning-tab" data-toggle="tab" href="#planning" role="tab" aria-controls="planning" aria-selected="false">Plannings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="salle-tab" data-toggle="tab" href="#salle" role="tab" aria-controls="salle" aria-selected="false">Salles</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" id="stats-tab" data-toggle="tab" href="#stats" role="tab" aria-controls="stats" aria-selected="false">Statistiques</a>
                        </li>
                    </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="dico" role="tabpanel" aria-labelledby="dico-tab">
                        <div class="row">
                            <div class="col-2">        
                                <div id="sidebarDico" style="height: 100px; width: 100%;"></div>
                            </div>
                            <div class="col-3">        
                                <div id="detailsDico" style="height: 100px; width: 100%;"></div>
                            </div>
                            <div class="col-3">
                                <div class="row">
                                    <div id="detailsItem" style="height: 100px; width: 100%;"></div>
                                </div>        
                                <div class="row">
                                    <div id="detailsGen" style="height: 100px; width: 100%;"></div>
                                </div>        
                            </div>
                            <div class="col-4">        
                                <div id="txtGen" style="height: 100px; width: 100%;"></div>
                            </div>
                        </div>
                    </div>
                <div class="tab-pane fade" id="planning" role="tabpanel" aria-labelledby="planning-tab">

                </div>
                <div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stat-tab">
                    <div class="w2ui-field">
                        <label>Période :</label>
                        <div> <input type="dateDeb"> - <input type="dateFin"> </div>
                    </div>
                    <div id="cal-heatmap" ></div>
                    
                </div>
                <div class="tab-pane fade" id="etudiant" role="tabpanel" aria-labelledby="etudiant-tab">

                </div>
                <div class="tab-pane fade" id="salle" role="tabpanel" aria-labelledby="salle-tab">

                </div>
                
                </div>                        
            </div>
        </div>

    </div>

    <!-- Fenêtre modale pour l'augmentation des heures -->
    <div class="modal fade" id="modChangeHeure" tabindex="-1" role="dialog" aria-labelledby="modChangeHeureLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modChangeHeureLabel">Modifier les heures de<span class="modalTitle" id="modChangeHeureInt"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="rngHeureNb"><span class="modalTitle" id="modChangeHeureNb"></span>heure(s) pour<span class="modalTitle" id="modChangeHeureCour"></span></label>
                        <input type="range" class="form-control-range" id="rngHeureNb" min="1" max="150" style="width:100%" >
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                <button type="button" class="btn btn-primary">Valider</button>
            </div>
            </div>
        </div>
    </div>

    <!-- Fenêtre modale pour le choix d'un fichier -->
    <div class="modal fade" id="modGetFic" tabindex="-1" role="dialog" aria-labelledby="modGetFicLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modGetFicLabel">Importer le fichier des données<span class="modalTitle" id="modGetFicInt"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="w2ui-field">
                    <div style="margin-left: 0px;" > <input style="width:100%;" id="fileImport"> </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                <button id="btnValidImport" type="button" class="btn btn-primary">Valider</button>
            </div>
            </div>
        </div>
    </div>

    <!-- Fenêtre modale pour l'ajout d'une UE -->
    <div class="modal fade" id="modAjoutUE" tabindex="-1" role="dialog" aria-labelledby="modAjoutUELabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modAjoutUELabel">Ajouter une UE<span class="modalTitle" id="modAjoutUEInt"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="inptUEHelp">Nom de l'UE</label>
                    <input type="text" class="form-control" id="inptUE" aria-describedby="inptUEHelp" placeholder="saisir le nom">
                    <small id="inptUEHelp" class="form-text text-muted">Merci de ne pas être trop long.</small>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                <button id="btnValidAjoutUE" type="button" class="btn btn-primary">Valider</button>
            </div>
            </div>
        </div>
    </div>

    <!-- Fenêtre modale pour l'ajout ou la modication d'une EC -->
    <div class="modal fade" id="modAjoutEC" tabindex="-1" role="dialog" aria-labelledby="modAjoutECLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modAjoutECLabel">Ajouter une UE<span class="modalTitle" id="modAjoutECInt"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="gridEC" style="width: 100%; height:500px;"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                <button id="btnValidAjoutEC" type="button" class="btn btn-primary">Valider</button>
            </div>
            </div>
        </div>
    </div>

    <!-- Fenêtre modale pour le temps de chargement -->
    <div class="modal fade" id="modWait" tabindex="-1" role="dialog" aria-labelledby="modWaitLbl" aria-hidden="true">
        <div class="modal-dialog modal-full" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modWaitLbl">Merci de patienter...</h5>
                </div>
                <div class="modal-body" style="height: 180px;">
                    <div id="loader" style="display:block;"></div>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
    "use strict";
    var contentHeight, sidebarDico, grids, rsGen;
$(function () {
    contentHeight = getContentHeight();
    getInitData();

    sidebarDico = {
        name       : 'sidebarDico',
        style      : 'height:'+contentHeight+'px;',
        topHTML    : '<div style="background-color: #eee; padding: 10px 5px; border-bottom: 1px solid silver">Liste des dictionnaires</div>',
        nodes : [],
        onClick: function(event) {
            let d = event.target.split('-');
            if(d[0]!='dicoGen' && d[0]!='dicoType'){
                showDico(d[0],d[1]);
            }
            console.log(event);
        }
    };
    grids = {'concepts':{ 
            name: 'gridDico', 
            style      : 'height:'+contentHeight+'px;',
            header: 'Concepts du dico',		
            show: { 
                header			: true,		
                toolbar			: true,
                toolbarReload   : false,
                toolbarColumns  : false,
                toolbarSearch   : true,
                toolbarAdd      : true,
                toolbarDelete   : true,
                toolbarSave		: false,
                selectColumn	: false,
                footer			: true,
            },
            columns: [         
                { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
                { field: 'lib', caption: 'Concept', size: '100%', sortable: true, resizable: true},
                { field: 'type', caption: 'Type', size: '100px', sortable: true, resizable: true},
            ],
            multiSearch: true,
            searches: [
                { field: 'recid', caption: 'ID', type: 'text', hidden:false},
                { field: 'lib', caption: 'Concept', type: 'text', hidden:false},
                { field: 'type', caption: 'Type', type: 'text', hidden:false},
            ],				
            toolbar: {
                items: [
                    { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' },
                    { id: 'genConcept', type: 'button', caption: 'Générer', icon: 'fa-file' },
                ],
                onClick: function (event) {
                    if (event.target == 'export') {
                        open(urlP+'export?obj=venteISBN',"_blank")
                    }
                    if (event.target == 'genConcept') {
                        open(urlP+'export?obj=venteISBN',"_blank")
                    }
                }
            },
            records: [],
            onSelect: function (event) {
                event.onComplete = function () {
                    var s = w2ui['gridDico'].getSelection();
                    if(s.length){
                        showDicoItem(w2ui[event.target].get(s[0]));
                    }
                }
            },
            onUnselect: function (event) {
                event.onComplete = function () {
                    w2ui['gridDetail'].records = rsGen;
                    w2ui['gridDetail'].refresh();
                }
            },	    
            onAdd: function(event) {
                console.log(event);
            }			    
        },
        'genDetails':{ 
            name: 'gridGenDetail', 
            style      : 'height:'+(contentHeight/2)+'px;',
            header: "Générateurs de l'item",		
            show: { 
                header			: true,		
                toolbar			: true,
                toolbarReload   : false,
                toolbarColumns  : false,
                toolbarSearch   : false,
                toolbarAdd      : true,
                toolbarDelete   : true,
                toolbarSave		: false,
                selectColumn	: false,
                footer			: true,
            },
            columns: [         
                { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
                { field: 'valeur', caption: 'Valeur', size: '100%', sortable: true, resizable: true},
            ],
            toolbar: {
                items: [
                    { id: 'genItem', type: 'button', caption: 'Générer item', icon: 'fa-file' }
                ],
                onClick: function (event) {
                    if (event.target == 'genItem') {
                        open(urlP+'export?obj=venteISBN',"_blank")
                    }
                }
            },
            records: [],
            onSelect: function (event) {
                event.onComplete = function () {
                    console.log(event);
                }
            },	 
            onUnselect: function (event) {
                event.onComplete = function () {
                    console.log(event);
                }
            },	    
            onAdd: function(event) {
                console.log(event);
            }			    
        },
        'aDetails':{ 
            name: 'gridADetail', 
            style      : 'height:'+(contentHeight/2)+'px;',
            header: 'Adjectifs',		
            show: { 
                header			: true,		
                toolbar			: true,
                toolbarReload   : false,
                toolbarColumns  : false,
                toolbarSearch   : false,
                toolbarAdd      : true,
                toolbarDelete   : true,
                toolbarSave		: false,
                selectColumn	: false,
                footer			: true,
            },
            columns: [         
                { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
                { field: 'elision', caption: 'elision', size: '50px', sortable: true, resizable: true},
                { field: 'prefix', caption: 'prefix', size: '100%', sortable: true, resizable: true},
                { field: 'f_p', caption: 'f p', size: '50px', sortable: true, resizable: true},
                { field: 'f_s', caption: 'f s', size: '50px', sortable: true, resizable: true},
                { field: 'm_p', caption: 'm p', size: '50px', sortable: true, resizable: true},
                { field: 'm_s', caption: 'm s', size: '50px', sortable: true, resizable: true},
            ],
            multiSearch: false,
            toolbar: {
                items: [
                    { id: 'genItem', type: 'button', caption: 'Générer item', icon: 'fa-file' }
                ],
                onClick: function (event) {
                    if (event.target == 'genItem') {
                        open(urlP+'export?obj=venteISBN',"_blank")
                    }
                }
            },
            records: [],
            onSelect: function (event) {
                event.onComplete = function () {
                    console.log(event);
                }
            },	 
            onUnselect: function (event) {
                event.onComplete = function () {
                    console.log(event);
                }
            },	    
            onAdd: function(event) {
                console.log(event);
            }			    
        }                        
    }
});

function getInitData(){

    var urls = ['../generateur/api?v=r&o=oeuvre', '../generateur/api?v=r&o=uti'];

    Promise.all(urls.map(url => d3.json(url))).then(function(values) {
        //console.log(values)
        initMenuOeuvre(values[0]);
    });

    
}

function initMenuOeuvre(rs){
    d3.select('#ddOeuvreItem').selectAll('a').data(rs).enter()
        .append('a')
        .attr('id', function (d) {
            return 'mnuId_'+d['recid'];})
        .attr('class','dropdown-item')
        .html(function (d) {                            
            return d['lib'];})
        .on('click',function(s){
            showListeDico(s);
        });
}

function showListeDico(o) {
    //TODO:gérer la fin de l'affichage pour lancer ajax $('#modWait').modal('show');
    if(w2ui['sidebarDico'])w2ui['sidebarDico'].destroy();

    //
    $.ajax({
        url: '../generateur/api?v=r&o=dico&idOeu='+o.recid,
        dataType: "json",
        method: "GET",
        error: function (error) {
            console.log("Erreur : " + error.responseText);
            $('#modWait').modal('hide');
        },
        success: function (data) {
            //console.log(data);
            //construction de l'arbre des dicos
            var gDico = Array.from(d3.group(data, d => d.general, d => d.type));
            var nodes = [];
            gDico.forEach(function(d,i){
                var nG = { id: 'dicoGen-'+i, text: d[0] == "0" ? "oeuvres" : "généraux" , img: 'fa-home', expanded: true, group: true, nodes: []};
                var arrT = Array.from(d[1]);
                arrT.forEach(function(t,j){
                    var nT = { id: 'dicoType-'+i+'-'+j, text: t[0], img: 'icon-folder', expanded: true, nodes: []};
                    t[1].forEach(function(dic){
                        nT.nodes.push({ id: dic.type+'-'+dic.recid, text: dic.nom, img: 'fa-star-empty'})
                    })
                    nG.nodes.push(nT);
                })
                nodes.push(nG);
                
            });
            sidebarDico.nodes = nodes;
            $('#sidebarDico').w2sidebar(sidebarDico);
            //$('#modWait').modal('hide');
        }
    });
}

function showDico(type, id) {
    //TODO:gérer la fin de l'affichage pour lancer ajax $('#modWait').modal('show');
    //initialise les grids
    if(w2ui[grids[type].name])w2ui[grids[type].name].destroy();
    if(w2ui[grids['aDetails'].name])w2ui[grids['aDetails'].name].destroy();
    if(w2ui[grids['genDetails'].name])w2ui[grids['genDetails'].name].destroy();
    
    //
    $.ajax({
        url: '../generateur/api?v=r&o=dico&idDico='+id+'&type='+type,
        dataType: "json",
        method: "GET",
        error: function (error) {
            console.log("Erreur : " + error.responseText);
            $('#modWait').modal('hide');
        },
        success: function (data) {
            //console.log(data);
            //construction du grid des concepts                      
            grids[type].records = data;
            $('#detailsDico').w2grid(grids[type]);

            //$('#modWait').modal('hide');
        }
    });
}

function showDicoItem(item) {
    if(w2ui[grids[item.type+'Details'].name])w2ui[grids[item.type+'Details'].name].destroy();
    if(w2ui[grids['genDetails'].name])w2ui[grids['genDetails'].name].destroy();

    //
    $.ajax({
        url: '../generateur/api?v=r&o=dico&idConcept='+item.recid+'&type='+item.type ,
        dataType: "json",
        method: "GET",
        error: function (error) {
            console.log("Erreur : " + error.responseText);
            $('#modWait').modal('hide');
        },
        success: function (data) {
            //console.log(data);
            //construction des grids                       
            grids[item.type+'Details'].records = data[item.type];
            grids['genDetails'].records = data['gen'];
            $('#detailsItem').w2grid(grids[item.type+'Details']);
            $('#detailsGen').w2grid(grids['genDetails']);

            
            //$('#modWait').modal('hide');
        }
    });
}

function getContentHeight(){
    return window.innerHeight 
        - document.getElementById('myTab').clientHeight 
        - document.getElementById('nbMain').clientHeight;
}

    </script>
  </body>
</html>