<html>
	<head>
		<title>Visualiser la territorialité des productions artistiques</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="../js/labels.js"></script>
		<script type="text/javascript" src="../js/ruler.js"></script>
		<script type="text/javascript" src="../js/d3.v2.js"></script>
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type='text/javascript' src="../js/tagcloud.js"></script>
		<script type='text/javascript' src="../js/d3.layout.cloud.js"></script>
		<script type="text/javascript" src="../js/heatmap.js"></script>
<meta name="Description" CONTENT=">Visualiser la territorialité des productions artistiques"/>
<meta name="Keywords" CONTENT=">Visualisation territoire art individu frontière"/>
<meta name="Author" CONTENT="Samuel Szoniecky"/>
<meta name="verify-v1" content="WsAmN5yAjLkY3+8UmcwheVwnclyQfENPneHC3DSiGAA=" />
<meta name="google-site-verification" content="4jXavF3D3d2PagHqRI0Jsih46vbJj1SDLr7KY8TtaGs" />

<link rel="stylesheet" href="../css/frontieres_classement.css" type="text/css" />


<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-3573757-11");
pageTracker._trackPageview();
} catch(err) {}
</script>
		
		<script type="text/javascript">

		var db = "flux_frontieres";
		var arrData = <?php echo json_encode($this->data);?>;
		var arrTof = [];
		var iTof = 0, posiClic, posiNote;
		var choix = false;
		var map;

		function init(){
			//classement de toute les photos
			arrData['indTerreForDoc'].forEach(function(d) {
				arrTof[d.doc_id] = {"id":d.doc_id,"url":d.url,"geo":1,"geo":0,"tag":1,"concept":0};				
			});
			arrData['indTerreTagForDoc'].forEach(function(d) {
				if(arrTof[d.doc_id]){
					arrTof[d.doc_id].tag = 1;				
				}else{
					arrTof[d.doc_id] = {"id":d.doc_id,"url":d.url,"geo":0,"tag":1,"concept":0};				
				}		
			});
			arrData['indTerreConcept'].forEach(function(d) {
				if(arrTof[d.doc_id]){
					arrTof[d.doc_id].concept = 1;				
				}else{
					arrTof[d.doc_id] = {"id":d.doc_id,"url":d.url,"geo":0,"tag":0,"concept":1};				
				}		
			});
			//ajoute les photos
			var dTofs = d3.select('#tofs');
			arrTof.forEach(function(d) {
				if(d.url=="")return;
				dTofs.append("img")
					.attr("id", "tof_"+d.id)
					.attr("src", d.url)
					.attr("class", "tof_mini");
				var t = document.getElementById("tof_"+d.id);
				t.addEventListener("onclick", showLinks, true);		
			});
			
			var t = document.getElementById("map_svg");
			t.addEventListener("onclick", showLinks, true);		
			
			getGeo(document.getElementById("map_geo"));
		}


		function showLinks(o){
			var rr = d3.select('#rectRed')
				.attr("x", o.offsetLeft)
		  		.attr("y", o.offsetTop);
			
		}
		
		</script>
	</head>
	<body onload="init();">	
		<div id="main">
			<h1>Visualiser la territorialité des productions artistiques</h1>
			<div id="navigtofs">
				<table>
					<tr>
						<td>
							<div class="bloc"><img src="../img/prev.jpg" onclick='prevTof();' /></div>
						</td>
						<td>
							<div id="tofs"></div>
						</td>
						<td>
							<div class="bloc"><img src="../img/next.jpg" onclick='nextTof();' /></div>
						</td>
					</tr>
				</table>
			</div>
			<div id="map_geo"></div>
			<div id="map_tagcloud"></div>			
		</div>
  		<div id="map_svg">
			<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" >
		    	<rect id="rectRed" x="10" y="10" width="100" height="20" style="fill:red"/>
			</svg>		
		</div>
  
		<script type="text/javascript" src="../js/frontieres.js"></script>
	</body>
</html>