<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="js/labels.js"></script>
		<script type="text/javascript" src="js/ruler.js"></script>
		<script type="text/javascript" src="js/d3.v2.js"></script>
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type='text/javascript' src="js/tagcloud.js"></script>
		<script type='text/javascript' src="js/d3.layout.cloud.js"></script>
		<script type="text/javascript">

		var arrTof = <?php echo json_encode($this->arr);?>;
		var iTof = 0, posiClic, posiNote;
		var choix = false;
		var map;
				
		function start() {
			var myOptions = {
			  zoom: 1,
			  center:  new google.maps.LatLng(0,0) ,
			  mapTypeId: google.maps.MapTypeId.ROADMAP		
			};
			
			map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);


			google.maps.event.addListener(map, 'click', function(mouseEvent) {
				if(!choix){					
					var posiTof = new google.maps.LatLng(arrTof[iTof]['lat'], arrTof[iTof]['lng']);
					removeRuler();
					posiClic = mouseEvent.latLng;
					addruler(posiClic, posiTof);
					choix = true;
					savePosition();
				}
			});

			chargeTof();
		}

		function removeRuler() {
			//supprime les règle sur la carte
			if(ruler1) ruler1.setMap(null);
			if(ruler2) ruler2.setMap(null);
			if(rulerpoly) rulerpoly.setMap(null);
			if(ruler1label) ruler1label.setMap(null);
			//supprime le tag cloud
			var dV = d3.select('#visTof');
			d3.select('#vis_tcIma').remove();
			dV.append("div").attr("id", "vis_tcIma");			
		}

		function chargeTof() {
			var dT = d3.select('#tof');
			d3.select('#selectTof').remove();
			var url = arrTof[iTof]['url'];
			dT.append("img")
				.attr("id", "selectTof")
				.attr("src", url);
			choix = false;
			
		}	
		
		function nextTof() {
			iTof++;
			if(iTof == arrTof.length) iTof = 0;
			removeRuler();
			chargeTof();
			map.setOptions({zoom: 1,center:new google.maps.LatLng(0,0)});
		}

		function savePosition() {
			var p = {"idDoc":arrTof[iTof]['doc_id'], "lat":posiClic.lat(), "lng":posiClic.lng(), "zoom":map.getZoom(), "note":posiNote};
			$.post("frontieres/ajout", p,
					 function(data){
				 		//affiche le tag cloud
		 				var tcg	= new tagcloud({idDoc:"tcIma", data:data, w:600, h:300, colorTag:'white', verif:true});
					 }, "json");
		}
		
		</script>
		<style>
		body { font-size: 14px; font-family:arial; line-height:20px;background-color:black;color:white}
		#main {text-align:center;margin-left: auto;margin-right: auto;width:1200px} 
		#map_canvas { float:left; width:600px; height:300px;}
		#tof {width:600px; height:600px;}
		</style>
	</head>
	<body onload="start();">
		<div id="main">
			<h1>Evaluation de la territorialité des productions artistiques</h1>
				<table>
					<tr>
						<th>Cliquez sur l'oeuvre pour passer à la suivante</th>
						<th>Cliquez sur la carte pour situer l'oeuvre</th>
					</tr>
					<tr>
						<td><div style="text-align:center;" id="tof"  onclick='nextTof();' ></div></td>
						<td style="vertical-align:text-top;">
							<div id="map_canvas"></div>
							<!-- <div>Cliquez sur les mots pour qualifier l'oeuvre</div>-->
							<div id="visTof">
								<!-- <div id="status_tcIma"></div>-->
								<div id="vis_tcIma"></div>
							</div>
						</td>
					</tr>
				</table>
				<br/>
		</div>
	</body>
</html>