<?php
	foreach($this->flux as $f){
		echo $f."<br/>"; 
	}
/*	
echo "<pre>";
system("/usr/local/bin/convert -version"); 
echo "FIN</pre>";
$array=array();
echo "<pre>";
exec("convert http://localhost/jdc/public/img/logoKeshif.png 2>&1", $array); 
echo "<br>".print_r($array)."<br>"; 
echo "FIN</pre>";
echo "<pre>";
exec("/usr/local/bin/convert /Users/samszo/Sites/jdc/public/img/logoKeshif.png 2>&1", $array); 
echo "<br>".print_r($array)."<br>"; 
echo "FIN</pre>";
*/