<?php					
if(!$this->html){
	echo json_encode($this->docs);
	return;
}	
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="Description" CONTENT=">Affichages des url enregstrées dans goo.gl"/>
		<meta name="Author" CONTENT="Samuel Szoniecky"/>
		<meta name="verify-v1" content="WsAmN5yAjLkY3+8UmcwheVwnclyQfENPneHC3DSiGAA=" />
		<meta name="google-site-verification" content="4jXavF3D3d2PagHqRI0Jsih46vbJj1SDLr7KY8TtaGs" />
		<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try {
		var pageTracker = _gat._getTracker("UA-3573757-11");
		pageTracker._trackPageview();
		} catch(err) {}
		</script>
	</head>
	<body>
		<div id="main">
			<table>
				<tr>
					<th>id</th>
					<th>titre</th>
					<th>url longue</th>
					<th>type de document</th>
					<th>url courte</th>
					<th>photo</th>
				</tr>
				<?php					
				foreach ($this->docs as $d){
					echo '<tr>';
					echo '<td>'.$d['doc_id'].'</td><td>'.$d['titre'].'</td><td>'.$d['url'].'</td><td>'.$d['type'].'</td><td>'.$d['dcurl'].'</td>'
						.'<td><img class="tof" src="'.$d['dpurl'].'" height="100px" />'.$d['dpurl'].'</td>';
					echo '</tr>';
				}
				?>
			</table>
		</div>
	</body>
</html>

