SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
 WHERE
 TABLE_NAME = 'site';
 -- REFERENCED_TABLE_SCHEMA = 'omeka_test' 
 -- AND REFERENCED_COLUMN_NAME = 'site.owner_id';


-- ALTER TABLE site DROP FOREIGN KEY FK_694309E47E3C61F9;
 
 