<?php
if(!$this->ajax){
	$prefUrl = "../";
	echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Editeur de réseaux d&#130;influences</title>
	<script type="text/javascript">
	    var prefUrl = "../";
	  	var setAutoComplet = true;
		var idBase = "'.$this->idBase.'";
		var uti = '.$this->uti.';
		var rsCribles = [];
		var rsGraphs = [];		
	</script>
    <link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
    <link rel="stylesheet" type="text/css" href="../font/font-awesome/font-awesome.css" />
	<script type="text/javascript" src="../js/d3.js"></script>
	<script type="text/javascript" src="../js/jquery.min.js"></script>
    <script type="text/javascript" src="../js/w2ui.js"></script>
	<script type="text/javascript" src="../js/editinflu/reseau.js"></script>
	<script type="text/javascript" src="../js/editinflu/flux.js"></script>
	<script type="text/javascript" src="../js/editinflu/view.js"></script>
	
  </head>
  
  <body >
';
}else{
	$prefUrl = "";
	echo '<script type="text/javascript">
	</script>';	
}
?>
    <link rel="stylesheet" href="<?php echo $prefUrl;?>css/grapheditor.css">
	<div id="viz"></div>
				
	</body>

  	<script type="text/javascript">
  	var connect = <?php echo $this->connect; ?>;
  	var arrGraphs;
  	var viz = document.getElementById("viz");  	
	var ajax = <?php echo $this->ajax ? 1 : 0; ?>;
	var lstGraph = document.getElementById('lstGraph');

	/*
	var nodes = [
	             {id: 0, reflexive: false, desc:"Trop bien"},
	             {id: 1, reflexive: true, desc:"oui oui" },
	             {id: 2, reflexive: false, desc:"d'la bombe"}
	           ],
           links = [
             {source: nodes[0], target: nodes[1], left: false, right: true },
             {source: nodes[1], target: nodes[2], left: false, right: true }
           ];
    */	
	var nodes = [],links = [], rs;	             
    dialogues = {
    		"noeud":document.getElementById('dlgNoeud')
    		,"lieu":document.getElementById('dlgLieu')
    		,"event":document.getElementById('dlgEvent')
    		,"acteur":document.getElementById('dlgActeur')
    		,"sauveDoc":document.getElementById('dlgSauveDoc')
    		,"message":document.getElementById('dlgMess')
    		
    		};

    // app starts here
	if(!ajax)showReseau(nodes, links);
	
  </script>
<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}
?>