<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Tweet Palette</title>
		<link rel="stylesheet" href="css/tweetpalette.css" />
	    <script type='text/javascript' src='js/d3.v2.js' ></script>
		<script type="text/javascript" src="js/heatmap.js"></script>
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/jquery.smart_autocomplete.js"></script>
<meta name="Description" CONTENT="cartographie pour twitter un événement"/>
<meta name="Keywords" CONTENT="cartographie ieml twitter pallette tweet"/>
<meta name="Author" CONTENT="Samuel Szoniecky"/>
<meta name="verify-v1" content="WsAmN5yAjLkY3+8UmcwheVwnclyQfENPneHC3DSiGAA=" />
<meta name="google-site-verification" content="4jXavF3D3d2PagHqRI0Jsih46vbJj1SDLr7KY8TtaGs" />
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-3573757-11");
pageTracker._trackPageview();
} catch(err) {}
</script>
	</head>
	<body>
		<div id="main">
			<div id="configArea">
				<h2>Tweet Palette</h2>
				<hr/>
				Utilisateur : <?php echo $this->identite; ?>
				-<a href="<?php echo '../public/auth/login?redir=tweetpalette&idBase='.$this->idBase; ?>">déconnexion</a>-
				<hr/>
				<div>
					<h4>Infos de l'évènement</h4>
					<label>Url : <input class="infoEvent" id="url_event" value="<?php echo $this->url; ?>" /></label>
					<!--  
					<input type="checkbox" id="filtrerUrl" onclick="getTweet();" <?php if($this->iframe) echo 'checked="checked"'; ?> />
					-->
					<div id="url_court" ></div>
					<label>Auteur : <input class="infoEvent" id="user_event" /></label>
					<!--  
					<input visible="false" type="checkbox" id="filtrerUti" onclick="getTweet();" />
					-->
					<label>Tag : <input class="infoEvent" id="tag_event" value="<?php echo $this->tag; ?>" /></label>
					<!--  
					<input visible="false" type="checkbox" id="filtrerTag" onclick="getTweet();" <?php if($this->iframe) echo 'checked="checked"'; ?> />
					-->
				</div>
				<hr/>
				<div>
					Palettes disponibles : 
					<select onchange="changePalette(this)" >
					  <option value="">Choisissez une palette</option>
					  <?php 
					  	//construction des options
					  	foreach ($this->palettes as $p) {
						  	echo "<option id='".$p["doc_id"]."' data='eval(".$p["data"].")' class='".$p["note"]."' value='".$p["url"]."'>".$p["titre"]."</option>";
					  	}
					  ?>
					</select>
				</div>
				<hr/>
				<div>
					Rôles disponibles : 
					<select onchange="changeRole(this)" >
					  <option value="">Choisissez un rôle</option>
					  <?php 
					  	//construction des options
					  	foreach ($this->roles as $r) {
						  	echo "<option value='".$r["role"]."'>".$r["role"]."</option>";
					  	}
					  ?>
					</select>
				</div>
				<hr/>
				<div>
					<label>Texte du tweet : <span id="taille_tweet" /></label>
					<textarea id="tweet_text" maxlength="140" ></textarea>
					<!--  
					<input visible="false" type="checkbox" id="showIeml" <?php if($this->iframe) echo 'checked="checked"'; ?> /> Affiche IEML
					-->
					<div id="gen">Enregistrer</div>
				</div>
			</div>
			<div id="svgArea">
				<div id="heatmapArea" />
				<img src="" id="png" />
				<div id="svg"></div>
			</div>
			
		</div>
		<script type="text/javascript">
		var idBase = '<?php echo $this->idBase; ?>';
		var idUti = <?php echo $this->idUti; ?>;
		var iframe = '<?php echo $this->iframe; ?>';
		
		//construction du tableau des coordonnées sémantiques
		<?php 
		  	//construction des options
		  	echo "var grilles =  [";
			foreach ($this->palettes as $p) {
			  	echo $p["data"].",";
		  	}
			echo "];";
		?>		
		</script>
		<script type="text/javascript" src="js/tweetpalette.js"></script>
	</body>
</html>