<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:dc="http://purl.org/dc/elements/1.1/">
    <rdf:Description rdf:about="urn:isbn:9782354800147 2354800142">
        <dc:title>Les lois de l'imitation des affects</dc:title>
        <dc:type>bookSection</dc:type>
        <dc:creator>Citton, Yves</dc:creator>
        <dc:publisher>Éd. Amsterdam</dc:publisher>
        <dc:date>2008</dc:date>
        <dc:identifier>ISBN 9782354800147 2354800142</dc:identifier>
    </rdf:Description>
</rdf:RDF>