<?php
	
?>
<!DOCTYPE HTML>
<!--
	Overflow 1.0 by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
	    <title>GAPAï - Interprétations proverbiales</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	    <meta name="generator" content="Google Web Designer 1.0.0.924">
		<meta name="Description" CONTENT="Appareil de capture sémantique pour l'interprétation de proverbes par des cartographies sémantiques"/>
		<meta name="Keywords" CONTENT="proverbe interprétation cartographie appareil capture sémantique"/>
		<meta name="Author" CONTENT="Samuel Szoniecky"/>
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic" rel="stylesheet" type="text/css" />
		<script src="js/jquery.min.js"></script>
		<script src="js/d3.v3.js"></script>
		<script src="js/gapaii/jquery.poptrox-2.2.js"></script>
		<script src="js/gapaii/skel.min.js"></script>
		<script src="js/gapaii/init.js"></script>
		<script src="js/gapaii/gapaii.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/gapaii/skel-noscript.css" />
			<link rel="stylesheet" href="css/gapaii/style.css" />
		</noscript>
		<script type="text/javascript">
			var idBase="<?php echo $this->idBase; ?>";
			var idUti=-1;				
		    var urlGen = "http://localhost/generateur/services/api.php?oeu=6";
	        function load(idDiv, idCpt) {
	            d3.text(urlGen+"&cpt="+idCpt, function(fragment) {
	                d3.select("#"+idDiv).html(fragment);
	            });
	        }
	    </script>
	</head>
	<body>

		<!-- Header -->
			<section id="header">
				<header>
					<h1>GAPAII</h1>
					<p>Interprétations Proverbiales</p>
				</header>
				<footer>
					<a href="#first" class="button style2 scrolly">Inscription</a>
					<a href="#second" class="button style2 scrolly">Connexion</a>
				</footer>
			</section>
		<!-- Feature 1 -->
			<article id="first" class="container box style1 right">
				<a href="http://ineedchemicalx.deviantart.com/art/Time-goes-by-too-fast-335982438" class="image full"><img src="img/gapaii/pic01.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Inscription</h2>
					</header>
					<form id="inscription" name="inscription" enctype="application/x-www-form-urlencoded" action="<?php echo WEB_ROOT;?>/public/auth/inscription" method="post">
						<div class="row half">
							<input type="hidden" id="ajax" name="ajax" value="true" />
							<input type="hidden" name="idBase" value="<?php echo $this->idBase; ?>" />
							<div class="6u"><input type="text" class="text" id="login" name="login" value="" placeholder="Login" /></div>
							<div class="6u"><input type="password" class="text" id="mdp" name="mdp" value="" placeholder="Mot de passe" /></div>
						</div>
						<div class="row half">
							<div class="12u">
								<input type="text" class="text" id="email" name="email" value="" placeholder="Email" />
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><input type="submit" class="button form" name="envoyer" id="boutonenvoyer" value="envoyer"></li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</article>
		
		<!-- Feature 2 -->
			<article id="second" class="container box style1 left">
				<a href="http://ineedchemicalx.deviantart.com/art/Time-goes-by-too-fast-335982438" class="image full"><img src="img/gapaii/pic01.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Connexion</h2>
					</header>
					<form id="connexion" name="connexion" enctype="application/x-www-form-urlencoded" action="<?php echo WEB_ROOT;?>/public/auth/login" method="post">
						<div class="row half">
							<input type="hidden" name="ajax" value="true" />
							<input type="hidden" name="idBase" value="<?php echo $this->idBase; ?>" />
							<div class="6u"><input type="text" class="text" name="login" value="" placeholder="Login" /></div>
							<div class="6u"><input type="password" class="text" name="password" value="" placeholder="Mot de passe" /></div>
						</div>
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><input type="submit" class="button form" name="submit" id="submit" value="Connexion"></li>
								</ul>
							</div>
						</div>
					</form>					
				</div>
			</article>

		<!-- Feature 2 -->
			<article class="container box style1 left">
				<a href="http://ineedchemicalx.deviantart.com/art/Kingdom-of-the-Wind-348268044" class="image full"><img src="img/gapaii/pic02.jpg" alt="" /></a>
				<div class="inner">
					<header>
						<h2>Proverbes</h2>
					</header>
					<form>
						<div class="row half">
							<div class="6u" id="genPro"><br/></div>
						</div>
						<div class="row">
							<div class="12u">
								<ul class="actions">
									<li><a class="button form" onclick="load('genPro', 157823)" >Génère</a></li>
								</ul>
							</div>
						</div>
					</form>					
				</div>
			</article>
		
		<!-- Portfolio -->
			<article class="container box style2">
				<header>
					<h2>Partenaires du projet</h2>
					<p></p>
				</header>
				<div class="inner gallery">
					<div class="row flush">
						<div class="3u"><a target="_blank" href="img/gapaii/fulls/02.jpg" class="image full"><img src="img/logoArtsH2H.png" alt="" title="LABEX ARTS H2H" /></a></div>
						<div class="3u"><a target="_blank" href="http://www.paragraphe.info" class="image full"><img src="img/logo_paragraphe.gif" alt="" title="Laboratoire Paragraphe" /></a></div>
						<div class="3u"><a target="_blank" href="img/gapaii/fulls/03.jpg" class="image full"><img src="img/logoDIPRALANG.png" alt="" title="Laboratoire DIPRALANG" /></a></div>
						<div class="3u"><a target="_blank" href="img/gapaii/fulls/04.jpg" class="image full"><img src="img/logoUMR7023.png" alt="" title="Laboratoire" /></a></div>
					</div>
				</div>
			</article>
		
		<section id="footer">
			<ul class="icons">
				<li><a href="#" class="icon icon-twitter solo"><span>Twitter</span></a></li>
				<li><a href="#" class="icon icon-facebook solo"><span>Facebook</span></a></li>
				<li><a href="#" class="icon icon-google-plus solo"><span>Google+</span></a></li>
			</ul>
			<div class="copyright">
				<ul class="menu">
					<li><a target="_blank" href="http://creativecommons.org/licenses/by/2.0/fr/" ><img height="16px" src="img/by.png" alt="" title="creative commons by" /></a></li>
					<li>Design: <a target="_blank" href="http://html5up.net/">HTML5 UP</a></li>
					<li>Demo Images: <a target="_blank" href="http://ineedchemicalx.deviantart.com">Felicia Simion</a></li>
				</ul>
			</div>
		</section>

	</body>
</html>