<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="../css/arbre.css" />
	<link rel="stylesheet" type="text/css" href="../css/colorbrewer.css" />
	<link rel="stylesheet" type="text/css" href="../css/colorbrewer.stroke.css" />

	<script type='text/javascript' src="../js/d3.v3.js"></script>

	<script type='text/javascript' src="../js/graine.js"></script>
	<script type='text/javascript' src="../js/branche.js"></script>
	<script type='text/javascript' src="../js/racine.js"></script>
	<script type='text/javascript' src="../js/bulle.js"></script>
	<script type='text/javascript' src="../js/tagcloud.js"></script>
	<script type='text/javascript' src="../js/d3.layout.cloud.js"></script>
</head>
<body id="bodyGlobal" >
	<div id="divGlobal">
		<div id="divCenter">
			<h1>Explorateur allégorique</h1>
			<div id="divTag">
				<h2>Concepts - terroirs</h2>
				<div id="divTagDewey"></div>
				<div id="divTagCloud">
					<div id="status_gTC"></div>
					<div id="select_txt_gTC"></div>
				</div>
			</div>
			<div id="divUtiExa">
				<h2>Acteurs - graines</h2>
			</div>
			<div id="divDocBranches">
				<h2>Documents - branches</h2>
			</div>
		</div>	
	</div>	
	<script type="text/javascript">
       	var divTagDewey = d3.select("#divTagDewey");
       	var divTagCloud = d3.select("#divTagCloud");
       	var divUtiExa = d3.select("#divUtiExa");
       	var divDocBranches = d3.select("#divDocBranches");
		var tc, grn, brc;
		
		var bulleDewey = new bulle({id:"bulleDewey", div:divTagDewey, w:300, h:300, r:300, urlJson:"../biblio/dewey", urlBookDetail:"../biblio/bookdetail?idsDoc="});

		function chargeTag(tag){
			brc.filtreTag(tag);
		}

	</script>	
  </body>
</html>	