<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>
      Google Visualization API Sample
    </title>
    <script type="text/javascript" src="//www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">
      function drawVisualization() {
        var data = google.visualization.arrayToDataTable([
          ['Base de données',  'ICE 1', 'ICE 2', 'ICE 3', 'ICE 4'],
          ['Initiale', 9.39573E-34, 3.75829E-33, 1.55593E-29, 7.75614E-15],
          ['Finale', 9.49627E-34, 3.79851E-33, 1.57258E-29, 8.34262E-15],
          ['SIC - TIC', 9.10383E-31, 3.64153E-30, 1.50759E-26, 2.61346E-13],
        ]);
        var options = {
          width: 600, height: 400,
          title: 'Comparaison des complexités existentielles',
          vAxis: {title: 'Somme des dimensions',logScale:true, ticks: [1E-35,1E-25,1E-20,1E-10]},
          isStacked: true,
          legend: { position: 'bottom' },
          connectSteps: true          
        };
      
        var chart = new google.visualization.SteppedAreaChart(document.getElementById('visualization'));
        chart.draw(data, options);
      }
      

      google.setOnLoadCallback(drawVisualization);
    </script>
  </head>
  <body style="font-family: Arial;border: 0 none;">
    <div id="visualization" style="width: 600px; height: 400px;"></div>
  </body>
</html>