<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->titre; ?></title>
  	<script type="text/javascript" src="../js/d3.v3.min.js"></script>
	<script type="text/javascript" src="../js/dimple.v2.1.0.min.js"></script>
  </head>
  
  <body ><div id="chartContainer">
  <script type="text/javascript">
    var svg = dimple.newSvg("#chartContainer", 590, 400);
    d3.tsv("../data/example_data.tsv", function (data) {
    //d3.json("../spip/formgetdonnees?idBase=spip_dimi1415&idForm=3", function (data) {

    		//reformatage des données
    		var dt = [];
		data.donnees.forEach(function(d){
			dt.push({"Auteur":d["auteurArt"],"Compétence":"Développement","Niveau":d["Niveau Développement"]});
			dt.push({"Auteur":d["auteurArt"],"Compétence":"Gestion de projet","Niveau":d["Niveau Gestion de projet"]});
			dt.push({"Auteur":d["auteurArt"],"Compétence":"Logiciel PAO","Niveau":d["Niveau Logiciels PAO"]});
		});          
      var myChart = new dimple.chart(svg, dt);
      myChart.setBounds(90, 50, 480, 310)
      //myChart.addCategoryAxis("x", ["Niveau Développement","Niveau Gestion de projet","Niveau Logiciels PAO"]);
      //myChart.addCategoryAxis("x", ["auteurEval","Note Générale"]);
      myChart.addCategoryAxis("x", ["Compétence"]);
      myChart.addCategoryAxis("y", "Auteur");
      myChart.addSeries("Niveau", dimple.plot.bar);
      myChart.addLegend(100, 10, 480, 20, "right");
      myChart.draw();
    });
  </script>
</div>
				
	</body>
</html>