<html>
<head>

<link href="../js/conceptmap/concept-map.css" rel="stylesheet"></link>

<script src="../js/jquery.min.js" type="text/javascript"></script>
<script src="../js/d3.v3.min.js" type="text/javascript"></script>
<script src="../js/conceptmap/packages.js" type="text/javascript"></script>
<script src="../js/conceptmap/concept-map.js" type="text/javascript"></script>

<script>
$(function(){
	plotConceptMap();
});
function plotConceptMap()
{
	d3.json("../data/metadata.json", function(dataJson) {
		var plot = new ConceptMap("graph", "graph-info", dataJson);
	});
}
</script>
<style>
body{
padding-top: 10px;
}
</style>
</head>
<body>
				<div id="graph" class="conceptmap" ></div>
				<div id="graph-info"></div>
</body>
</html>