<!DOCTYPE html>
<meta charset="utf-8">
<style>

path {
  stroke: #fff;
}

</style>
<body>
<script src="../js/d3.v3.min.js"></script>
<script>

var width = 960,
    height = 700,
    radius = (Math.min(width, height) / 2) - 10;

var formatNumber = d3.format(",d");

var x = d3.scale.linear()
    .range([0, 2 * Math.PI]);

var y = d3.scale.sqrt()
    .range([0, radius]);

var color = d3.scale.category20c();

var partition = d3.layout.partition()
    .value(function(d) { return d.size; });

var arc = d3.svg.arc()
    .startAngle(function(d) {         
        var a = Math.max(0, Math.min(2 * Math.PI, x(d.x))); 
        a = d.depth > 1 && d.parent && d.parent.children ? x(0.5) : 0;  
        return a;
        })
    .endAngle(function(d) { 
        var a = Math.max(0, Math.min(2 * Math.PI, x(d.x + d.dx))); 
        a = d.depth > 0 && d.children ? x(0.5) : x(1); 
        return a;
        })
    .innerRadius(function(d) { 
        var r = Math.max(0, y(d.y));
        var r1 = Math.max(0, y(d.debut));
        return r1; 
        })
    .outerRadius(function(d) { 
        var r = Math.max(0, y(d.y + d.dy));
        var r1 = Math.max(0, y(d.fin));
        return r1; 
        });

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
  .append("g")
    .attr("transform", "translate(" + width / 2 + "," + (height / 2) + ")");

d3.json('<?php echo $this->urlStats; ?>', function(error, root) {
  if (error) throw error;
  //met à jour le domaine y pour la hauteur de l'arc
  y.domain([root.min, root.max]);
    
  svg.selectAll("path")
      .data(partition.nodes(root))
    .enter().append("path")
      .attr("d", arc)
      .style("fill", function(d) { return "blue";//color((d.children ? d : d.parent).name);
      	 })
      .style("opacity",function(d) { 
          return (d.depth*0.3);
   	 	})
      .on("click", click)
    .append("title")
      .text(function(d) { return d.name + "\n" + formatNumber(d.value); });
});

function click(d) {
	/*Zoom
  svg.transition()
      .duration(750)
      .tween("scale", function() {
        var xd = d3.interpolate(x.domain(), [d.x, d.x + d.dx]),
            yd = d3.interpolate(y.domain(), [d.debut, 1]),
            yr = d3.interpolate(y.range(), [20, radius]);
        return function(t) { x.domain(xd(t)); y.domain(yd(t)).range(yr(t)); };
      })
    .selectAll("path")
      .attrTween("d", function(d) { return function() { return arc(d); }; });
    */
}

d3.select(self.frameElement).style("height", height + "px");

</script>
	
  </body>
</html>	