<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Gallerie dynamique de photos</title>
<style>
html, body {
	height: 100%;
}

#graph {
	
}

.node {
	position: absolute;
	background-size: cover;
	border-style: none;
	border-color: red;
}

.curseur {
	position: absolute;
	width: 100px;
	height: 100px;
	left: 0px;
	top: 0px;
	z-index: 110;
}

#curseurSelect {
	font-size: 56px;
	text-align: center;
}

.choix {
	position: absolute;
	width: 100%;
	height: 100%;
	left: 0px;
	top: 0px;
	z-index: 100;
}

.choixCarousel {
	position: absolute;
	width: 100%;
	height: 100%;
	left: 0px;
	top: 0px;
	z-index: 100;
}


.carousel .item {
	height: 300px;
}

.item img {
	position: absolute;
	top: 0;
	left: 0;
	min-height: 300px;
}
</style>

<!-- CSS -->
<link rel="stylesheet" type="text/css"
	href="../font/font-awesome/font-awesome.css" />
<link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
<script src="../js/d3.min.js"></script>
<script src="../js/jquery.min.js"></script>

</head>

<body>


<div class="card text-center">
  <div class="card-header">
		<nav class="navbar navbar-light bg-light">
			<span class="h1" class="navbar-brand mb-0">Evaluations émotionnelles</span>
		</nav>
  </div>
  <div class="card-body">
    <h2 class="card-title">Collections photographiques des Archives Nationales</h2>
    
	<div class="container-fluid">
		<div id="rowGen" class="row">
			<div class="col-4 hidden-md-down">
				<div id="carouselEvals" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators" id="car-ind">
						<!--  
    <li data-target="#carouselEvals" data-slide-to="0" class="active"></li>
    <li data-target="#carouselEvals" data-slide-to="1"></li>
   -->
					</ol>
					<div class="carousel-inner" id="car-inn">
						<!--  
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://localhost/ValArNum/omk/iiif-img/15314/1290,753,258,552/full/0/default.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h3>Titre 1</h3>
        <p>blbab</p>
      </div>
   </div>
    <div class="carousel-item">
      <img class="img-fluid" src="http://localhost/ValArNum/omk/iiif-img/15350/334,549,1612,1326/full/0/default.jpg" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h3>Titre 1</h3>
        <p>blbab</p>
      </div>
    </div>
    -->
					</div>
					<a class="carousel-control-prev" href="#carouselEvals"
						role="button" data-slide="prev"> <span
						class="carousel-control-prev-icon" aria-hidden="true"></span> <span
						class="sr-only">Previous</span>
					</a> <a class="carousel-control-next" href="#carouselEvals"
						role="button" data-slide="next"> <span
						class="carousel-control-next-icon" aria-hidden="true"></span> <span
						class="sr-only">Next</span>
					</a>
				</div>

			</div>
			<div class="col-8 hidden-md-down" id="graph">
				<div id="curseurPalette" class="curseur"></div>
				<div id="curseurSelect" class="curseur"></div>
			</div>
		</div>

	</div>
    
  </div>
  <div id="pied" class="card-footer text-muted">
			<h4>Conception &amp; réalisation : Samuel Szoniecky</h4>
			<h5>Merci à : </h5>
  </div>
</div>



	<script>
	//merci beaucoup à https://bl.ocks.org/shimizu/79409cca5bcc57c32ddae0a5f0a1a564
    "use strict"

    
    var data = [
        {id:"root",value:null},
        {id:"root.1",value:null,img:"http://localhost/ValArNum/omk/iiif-img/1569/340,600,150,400/600,1600/0/gray.png"},
        {id:"root.2",value:null,img:"http://localhost/ValArNum/omk/iiif-img/1563/full/full/0/gray.png"},
        {id:"root.3",value:null,img:"http://localhost/ValArNum/omk/iiif-img/1564/full/full/0/gray.png"},
        {id:"root.4",value:null,img:"http://localhost/ValArNum/omk/iiif-img/1562/full/full/0/gray.png"},
        {id:"root.5",value:null,img:"http://localhost/ValArNum/omk/iiif-img/1565/full/full/0/gray.png"},
    ]
	var q = '<?php echo $this->q; ?>';
  	d3.json("../flux/iiif?q="+q+"&idCol=<?php echo $this->idCol; ?>",function(dataOmk) {
 		data=dataOmk;
        if(q != 'getCollectionFaces')setInterval(draw, 8000);
 	    draw(); 	 		
 	}); 
 	        

	/*
	Chargement du curseur palette
	*/
	var curseurData = [
	 {idG:'g4351',idText:'tspan3891',en:'ecstasy',fr:'extase',color:'#ffe854',value:0,liens:['g4341'],niv:0}
  	,{idG:'g4398',idText:'tspan3836',en:'annoyance',fr:'gêne',color:'#ff8c8c',value:0,liens:['g4666'],niv:2}
  	,{idG:'g4403',idText:'tspan3840',en:'anger',fr:'colère',color:'#ff0000',value:0,liens:['g4398'],niv:1}
  	,{idG:'g4408',idText:'tspan3844',en:'rage',fr:'rage',color:'#d40000',value:0,liens:['g4403'],niv:0}
  	,{idG:'g4341',idText:'tspan3895',en:'joy',fr:'joie',color:'#ffff54',value:0,liens:['g4346'],niv:1}
  	,{idG:'g4346',idText:'tspan3899',en:'serenity',fr:'sérénité',color:'#ffffb1',value:0,liens:['g4600'],niv:2}
  	,{idG:'g4413',idText:'tspan3903',en:'terror',fr:'terreur',color:'#008000',value:0,liens:['g4418'],niv:0}
  	,{idG:'g4418',idText:'tspan3907',en:'fear',fr:'peur',color:'#009600',value:0,liens:['g4423'],niv:1}
  	,{idG:'g4423',idText:'tspan3911',en:'apprehension',fr:'appréhension',color:'#8cc68c',value:0,liens:['g4630'],niv:2}
  	,{idG:'g4383',idText:'tspan3915',en:'admiration',fr:'adoration',color:'#00b400',value:0,liens:['g4378'],niv:0}
  	,{idG:'g4378',idText:'tspan3919',en:'trust',fr:'confiance',color:'#54ff54',value:0,liens:['g4373'],niv:1}
  	,{idG:'g4373',idText:'tspan3923',en:'acceptance',fr:'résignation',color:'#8cff8c',value:0,liens:['g4613'],niv:2}
  	,{idG:'g4356',idText:'tspan3927',en:'vigilance',fr:'vigilance',color:'#ff7d00',value:0,liens:['g4388'],niv:0}
  	,{idG:'g4388',idText:'tspan3931',en:'anticipation',fr:'excitation',color:'#ffa854',value:0,liens:['g4393'],niv:1}
  	,{idG:'g4393',idText:'tspan3935',en:'interest',fr:'intérêt',color:'#ffc48c',value:0,liens:['g4675'],niv:2}
  	,{idG:'g4458',idText:'tspan3939',en:'boredom',fr:'ennui',color:'#ffc6ff',value:0,liens:['g4657'],niv:2}
  	,{idG:'g4463',idText:'tspan3943',en:'disgust',fr:'dégoût',color:'#ff54ff',value:0,liens:['g4458'],niv:1}
  	,{idG:'g4468',idText:'tspan3947',en:'loathing',fr:'aversion',color:'#de00de',value:0,liens:['g4463'],niv:0}
  	,{idG:'g4438',idText:'tspan3951',en:'amazement',fr:'stupéfaction',color:'#0089e0',value:0,liens:['g4433'],niv:0}
  	,{idG:'g4433',idText:'tspan3955',en:'surprise',fr:'surprise',color:'#59bdff',value:0,liens:['g4428'],niv:1}
  	,{idG:'g4428',idText:'tspan3959',en:'distraction',fr:'distraction',color:'#a5dbff',value:0,liens:['g4639'],niv:2}
  	,{idG:'g4448',idText:'tspan3828',en:'sadness',fr:'tristesse',color:'#5151ff',value:0,liens:['g4453'],niv:1}
  	,{idG:'g4443',idText:'tspan3832',en:'grief',fr:'chagrin',color:'#0000c8',value:0,liens:['g4448'],niv:0}
  	,{idG:'g4453',idText:'tspan3007',en:'pensiveness',fr:'songerie',color:'#8c8cff',value:0,liens:['g4648'],niv:2}  	
  	,{idG:'g4563',idText:'tspan4022',en:'disapproval',fr:'désapprobation',color:'url("#linearGradient5706")',value:0,liens:[],niv:4}
  	,{idG:'g4556',idText:'tspan4026',en:'remorse',fr:'remord',color:'url("#linearGradient5714")',value:0,liens:[],niv:4}
  	,{idG:'g4547',idText:'tspan4030',en:'contempt',fr:'mépris',color:'url("#linearGradient5722")',value:0,liens:[],niv:4}
  	,{idG:'g4542',idText:'tspan4034',en:'awe',fr:'crainte',color:'url("#linearGradient5698")',value:0,liens:[],niv:4}
  	,{idG:'g4535',idText:'tspan4038',en:'submission',fr:'soumission',color:'url("#linearGradient5690")',value:0,liens:[],niv:4}
  	,{idG:'g4568',idText:'tspan4042',en:'love',fr:'amour',color:'url("#linearGradient5682")',value:0,liens:[],niv:4}
  	,{idG:'g4506',idText:'tspan4046',en:'optimism',fr:'optimisme',color:'url("#linearGradient5674")',value:0,liens:[],niv:4}
  	,{idG:'g4523',idText:'tspan4050',en:'aggressiveness',fr:'aggressivité',color:'url("#linearGradient5730")',value:0,liens:[],niv:4}
  	,{idG:'g4666',color:'#ffc5c5',value:0,liens:['g4547','g4523'],niv:3}
  	,{idG:'g4675',color:'#ffe1c5',value:0,liens:['g4506','g4523'],niv:3}
  	,{idG:'g4600',color:'#feffdd',value:0,liens:['g4506','g4568'],niv:3}
  	,{idG:'g4613',color:'#c5ffc5',value:0,liens:['g4535','g4568'],niv:3}
  	,{idG:'g4630',color:'#c5e2c5',value:0,liens:['g4535','g4542'],niv:3}
  	,{idG:'g4639',color:'#d5eeff',value:0,liens:['g4563','g4542'],niv:3}
  	,{idG:'g4648',color:'#c5c5ff',value:0,liens:['g4563','g4556'],niv:3}
  	,{idG:'g4657',color:'#c5c5ff',value:0,liens:['g4547','g4556'],niv:3}
  	];	

	//création du lien vers le parent
	curseurData.forEach(function(p){
		p.liens.forEach(function(e){
			var ee = curseurData.filter(function(f){
				return f.idG == e;
			})[0];
			ee.parent = p;
		}) 
	});
	
	var onFlux=true, onSelect=false, onChoix=false, noCurseur, curSelect, rootTofs, tofSelect, tofEval=[], idSvg="svg3360", l, t
		, mousedownID, cChoix, rChoix = 10, wCurseur = 300, hCurseur = 300, w="715.41962", h="724.66992", padding = 30
		, svgChoix;
  
	//dimensionne la gallerie dynamique
	var pied = document.querySelector("#pied");
	var graph = document.querySelector("#graph");
    var width = graph.clientWidth;
    var height = window.innerHeight-graph.offsetTop-pied.offsetHeight-padding;
    d3.select("#rowGen").style("height", height+"px");
    var div = d3.select("#graph").append("div").attr("width", width).attr("height", height);
    var rdmCur = d3.randomUniform(curseurData.length-1);
    
    function showCurseurFragment(){
		if(onSelect)return;
        //cache les fonds des fragments
        d3.selectAll(".gCurseur").selectAll('path').style('fill-opacity',0);
 		//affiche un fragment aléatoire
        	curSelect = 	curseurData[parseInt(rdmCur())];
        d3.select("#"+curSelect.o.idG).selectAll('path').style('fill-opacity',1);
        showCurseurText(curSelect);        	        
    }

    function showCurseurText(d){
		//récupère la position du curseur
		var cP = d3.select("#curseurPalette");
        
  		//affiche le texte du curseur
		d3.select("#curseurSelect")
			.style('color',d.o.color)
        	    .text(d.o.fr);        
    }
        
    function draw() {

		//vérifie si'l faut stopper le flux
		if(!onFlux)return;

        //enlève les choix        
		d3.selectAll('.choix').remove();       
		
        randomize()
                
        var stratify = d3.stratify()
            .parentId(function(d) {return d.id.substring(0, d.id.lastIndexOf(".")); });

        rootTofs = stratify(data).sum(function(d) { return d.value })

        var treemap = d3.treemap()
            .tile(d3.treemapBinary)
            .size([width, height])
            .padding(1)
            .round(true);        

        treemap(rootTofs)
        drawTreemap(rootTofs)                
            
    }
    
    function randomize() {
        data.filter(function(d){ return d.id !== "root"})
            .forEach(function(d){
                //modifie la taille de la photo dans le treemap
                d.value = ~~(d3.randomUniform(1, 10)()); 
                //modifie la taille de la photo
                if(d.imgOmk){
                    var minPixel = 10;
                    if(q != 'getCollectionFaces'){ 
                        //calcul la taille de la photo
                        d.x1 = parseInt(d3.randomUniform(minPixel, d.width)());
                        d.x2 = parseInt(d3.randomUniform(minPixel, (d.width-d.x1-minPixel))());
                        d.y1 = parseInt(d3.randomUniform(minPixel, d.height)());
                        d.y2 = parseInt(d3.randomUniform(minPixel, (d.height-d.y1-minPixel))());
                        var s = parseInt(d3.randomUniform(1, 4)());
                        var w = (d.x1+d.x2) * s;
                        var h = (d.y1+d.y2) * s;
                        d.r = 0;
        	                d.imgAleaTot=d.imgOmk+'/'+d.x1+','+d.y1+','+d.x2+','+d.y2+'/'+w+','+h+'/'+d.r+'/default.jpg';
        	                d.imgAleaPosi=d.imgOmk+'/'+d.x1+','+d.y1+','+d.x2+','+d.y2+'/full/'+d.r+'/default.jpg';
        	                d.img=d.imgAleaPosi;
                    }else{
                         d.img=d.imgFull;
                         d.value = d.width*d.height;
                    }
	                /*
	                console.log(d.img);    	                
	                console.log(d.imgAleaTot);    	                
	                console.log(d.imgAleaPosi);    	                
	                */
                }
            })
    }
    
    
    function drawTreemap(root) {

        var node = div.selectAll(".node")
        		.data(root.children);
          
        var newNode = node.enter()
           .append("div").attr("class", "node")
	  	   ;

        node.merge(newNode)
            /*PROBLEME avec la réécriture des liens IIIF
            .transition()
            .duration(1000)
            */
            .attr('id',function(d) { 
                return 'div'+d.data.idOmk 
                })
            .style("left", function(d) { return d.x0 + "px" })
            .style("top", function(d) { return d.y0 + "px" })
            .style("width", function(d) { return (d.x1 - d.x0) + "px" })
            .style("height", function(d) { return (d.y1 - d.y0) + "px"})
            .style("background-image", function(d){ 
                //console.log(d.data.img);    	                                
                return "url("+d.data.img+")"
                })                    		
            .on('click',function(d, i){
    	  			//affiche le curseur selecteur
	  			console.log(d);
  			});
            
    }


	d3.xml("../svg/Plutchik-wheel.svg",function(node) { 
		//return true;
  		//importe le curseur
  		var importedNode = document.importNode(node.documentElement, true);
  		d3.select("#curseurPalette").node().appendChild(importedNode);	  
  		//redimensionne  		
		var svg = d3.select("#"+idSvg).transition().duration(0)
        	    .attr("width", wCurseur)
        	    .attr("height", hCurseur)
        		.attr("viewBox","0 0 "+w+" "+h);	
        //supprime le text
	    	d3.selectAll('text').remove();

	    	//ajoute la class aux éléments du curseur
		//cache les éléments qui ne sont pas de niveau 0
        curseurData.forEach(function(c){
	        d3.select("#"+c.idG)
	        		.attr('class','gCurseur')
	        		//.style('display',c.niv > 0 ? 'none' : 'inline')
	        		.selectAll('path')
	        			//.style('stroke','none')        		
	        			//.style('fill','none');	        		
	        			.style('fill-opacity',0)
	        			.style('stroke-opacity',1)
					.style('stroke','white');
        })	
        
		//ajoute les événements
		var curseurs = d3.selectAll('.gCurseur')
  			.data(curseurData)
  			.attr("oId",function(d,i){
		  		var e = d3.select(this);
		  		//ATENTION l'ordre de cuseurData n'est pas celui de la selection
		  		//il faut donc filtrer les datas pour les réattribuer
  	  			//console.log(i+" = "+d.idG+" : "+e.attr('id'));
  	  			var dt = curseurData.filter(function(c){
  	  	  			return c.idG == e.attr('id');
  	  			})[0];
  	  			d.o = dt;
  	  			return dt.idG;
  			})
			.on('mousemove',function(e){
	  			if(!onSelect)return;
		        onChoix = true;
			})  			
	  		.on('mouseenter',function(d, i){

	  			if(!onSelect)return;

	  			var p = "NO";
				if(d.o.parent) p = d.o.parent.idG;
				console.log("ENTER = "+curSelect.o.idG+' = '+d.o.idG+' : '+ p);       	    
		  		
                	showCurseurText(d);
                    		  		
				/*Masque les élements inutiles
				if(!d.o.parent || curSelect.idG != d.o.parent.idG){
					curSelect.o.liens.forEach(function(l){
        			        if(l != d.o.idG)	d3.select("#"+l).style('display','none');
            			});
				}	  			
				//affiche les élements enfants et parent
	  			d.o.liens.forEach(function(l){
        		        	d3.select("#"+l)
            	        		.style('display','inline');		  			
	  			});
	  			if(d.o.parent)d3.select("#"+d.o.parent.idG).style('display','inline');		  			
				*/
        	    
  			})
	  		.on('mouseout',function(d, i){		  		
	  			if(!onSelect)return;	  			
	  			if(mousedownID!=-1) {  //Only stop if exists
	  			     clearInterval(mousedownID);
	  			     mousedownID=-1;
	 	  			stockeChoix(d);    	  			  				  			     
	  			}
	    	  		//supprime le texte 
	  			d3.select("#curseurSelect")
		        	    .text("");
	  			curSelect = d;	    
				console.log("OUT = "+curSelect.o.idG+' = '+d.o.idG);       	    
  			})
	  		.on('mousedown',function(d, i){
	  			if(!onChoix)return;
	  			//merci à  https://stackoverflow.com/questions/15505272/javascript-while-mousedown
	  			if(mousedownID==-1){  //Prevent multimple loops!		  			
	  				curSelect = d;
        	  			var x = l+(wCurseur/2)-rChoix, y = t+(hCurseur/2)-rChoix;
        	  			//ajoute un cercle de la couleur
        	  			cChoix = d3.select('body').append("svg").attr("class","choix")
        	  				.append('circle')
        	  				.attr("cx",rChoix)
        	  				.attr("cy",rChoix)
        	  				.attr("r",rChoix)
        	  				.style('fill-opacity',0.3)       	  				
        	  				.style("fill",d.o.color)
        	  				.attr('transform', 'translate(' + x + ',' + y + ')')
        	  				;
	  			    mousedownID = setInterval(augmenteChoix, 100 /*execute every 100ms*/); 			     	  			    	  				
	  			}
	  		})
	  		.on('mouseup',function(d,i){
	  			if(!onChoix)return;
	  			if(mousedownID!=-1) {  //Only stop if exists
	  			     clearInterval(mousedownID);
	  			     mousedownID=-1;
	 	  			stockeChoix(d);    	  			  			
	  			}
  			});
		
		//lance l'animation de couleur
        setInterval(showCurseurFragment, 1000);

	  	
	});	  

	function augmenteChoix(){
		console.log('augmenteChoix '+cChoix.attr("r"));			
		//cache les fragment saufs celui slectionné
        d3.selectAll(".gCurseur").selectAll('path').style('fill-opacity',0);
        d3.select("#"+curSelect.o.idG).selectAll('path').style('fill-opacity',1);		
		cChoix.attr("r",parseInt(cChoix.attr("r"))+10);
	}
	function stockeChoix(d){
		console.log('stockeChoix');	
		if(!cChoix)return;
				
		//calcul la position du choix
		var x = l+(wCurseur/2)-rChoix, y = t+(hCurseur/2)-rChoix;

		//récupère l'évaluation pour la photo omk
		var to = tofEval.filter(function(d){
			return d.idOmk == tofSelect.data.idOmk
			});
		//enregistre les références de l'émotion dans la photo
		var ev = {'img':tofSelect.data.img
			,'x1':tofSelect.data.x1,'x2':tofSelect.data.x2,'y1':tofSelect.data.y1,'y2':tofSelect.data.y2
			,'cx':x,'cy':y,'r':cChoix.attr("r"),'d':d.o};
		//ajoute les échelles de la photo
		ev.echelleX = d3.scaleLinear().range([ev.x1, ev.x2]);
		ev.echelleY = d3.scaleLinear().range([ev.y1, ev.y2]);
	    //stocke l'avaluation	
		if(to.length > 0){
			 to[0].evals.push(ev);
		}else{
			tofEval.push({'idOmk':tofSelect.data.idOmk,'label':tofSelect.data.label,'original':tofSelect.data.original
				,'evals':[ev]
				});

			//vérifie s'il faut activer les photos
			var active = 'active';
			if(tofEval.length > 1){
				active = ''
				//$('.carousel').carousel('pause');
				//d3.select('#car-ind').selectAll('li').attr('class','');				
				//d3.selectAll('#car-inn').selectAll('div').attr('class','carousel-item');				
			}
			
			//Ajoute la photo à la gallerie
			var li = d3.select('#car-ind').append('li')
				.attr('data-target',"#carouselEvals")	
				.attr('data-slide-to',tofEval.length-1);
			if(active) li.attr('class',"active");	
			
			var item = d3.select('#car-inn')
				.append('div').attr('class','carousel-item '+active);
			item.append('img')
				.attr('id','carImg_'+tofSelect.data.idOmk)
				.attr('class','d-block w-100')
				.attr('src',tofSelect.data.imgFull);
			//ajoute le descriptif
			var block = item.append('div').attr('class','carousel-caption d-none d-md-block');
			block.append('h3').text(tofSelect.data.label);
			block.append('p').append('a').attr('href',tofSelect.data.original).attr('target','_blank').text('original');
			
		}
		

		if(tofEval.length == 1){
			$('.carousel').carousel();
			//ajoute le svg pour les cercle de choix
			svgChoix = d3.select('#carouselEvals').append('svg')			
				.attr('class','choixCarousel')
				.append('g').attr('id','gChoix');
			//ajoute la première évaluation
			var fEv = tofEval[0].evals[0];		
			  //met à jour l'échelle de la photo
			var carImg = d3.select("#carImg_"+tofSelect.data.idOmk);
			fEv.echelleX.domain([carImg.x, carImg.width]);
			fEv.echelleY.domain([carImg.y, carImg.height]);
				
			svgChoix.append('circle')					  
				.attr('cx',fEv.cx)
			  	.attr('cy',fEv.cy)					  
			  	.attr('r',fEv.r)
			  	.attr('fill',fEv.d.color);
			svgChoix.append('rect')					  
        			.attr('x',fEv.x1)
        		  	.attr('y',fEv.y1)					  
        		  	.attr('width',fEv.x2)
        		  	.attr('height',fEv.y2)
        		  	.attr('fill','none')
				.attr('stroke','red');
			//ajoute les événements
			$('#carouselEvals').on('slide.bs.carousel', function (e) {
				  console.log(e);
				  //récupère la définition des cercles
				  var te = tofEval[e.from].evals;
						  
				  //construction du rectangle de zoom
				  d3.select('#gChoix').selectAll('rect').data(te).enter()
				  	  .append('rect')
					  .attr('x',function(d){
						  return d.x1
						  })
					  .attr('y',function(d){return d.y1})
					  .attr("width", function(d){return d.x2})
		        	    	  .attr("height", function(d){return d.y2})
					  .attr('fill','none')
					  .attr('stroke','red');
				  //construction des cercles d'évaluation
				  d3.select('#gChoix').selectAll('circle').data(te).enter()
				  	  .append('circle')
					  .attr('cx',function(d){return d.cx})
					  .attr('cy',function(d){return d.cy})					  
					  .attr('r',function(d){return d.r})
					  .attr('fill',function(d){
						  return d.d.color
						  });
				  
				})
		}
		//$('.carousel').carousel('cycle');
		$('.carousel').carousel(tofEval.length-1);
		
		
		//augmente le Z-index du curseur pour que les événements soient pris en compte
		//d3.selectAll('.curseur').style('z-index',parseInt(cChoix.style("z-index"))+1);	
		//déselectionne toutes les photos
		d3.selectAll('.node').style('border-style','none');		
		tofSelect = false;
		//relache le curseur
		onSelect = false;	  			
		onChoix = false;
		onFlux = true;
	}

	//ajoute le déplacement suivant la souris
	d3.select('#graph')
		.on('mousedown',function(e){
    	        //affiche les fonds des fragments
    	        d3.selectAll(".gCurseur").selectAll('path').style('fill-opacity',1);
    	  		//commence la sélection en bloquant le curseur
    	  		onSelect = true;
    	  		//stop le flux d'image
    	  		onFlux = false;
    	  		//récupère la photo de dessous par filtrage des coordonnées
    	  		//car pas trouvé le moyen de le faire sur un event de la photo
    	  		//à cause de la séparation des div entre curseur et photo
    	  		var m = d3.mouse(this);    	  		
    	  		//var m = d3.event;    	  		
    			tofSelect = rootTofs.children.filter(function(d){
        	  		return m[0] > d.x0 && m[1] > d.y0 && m[0] < d.x1 && m[1] < d.y1;
        	  		//return m.x > d.x0 && m.y > d.y0 && m.x < d.x1 && m.y < d.y1;
    	  			})[0];
    	  		//met les bords en rouge
        	  	d3.select('#div'+tofSelect.data.idOmk).style('border-style','solid');		
			})
		.on('mousemove',function(e){
			if(onSelect)return;
			if(noCurseur)return;
			var mT = d3.mouse(this);
			var x = mT[0]-(wCurseur/2);
	        var y = mT[1]-(hCurseur/2);
	  		var m = d3.event;
	        l = m.x-(wCurseur/2);
	        t = m.y-(hCurseur/2);

			if(m.x < graph.offsetLeft)return;
			if(m.y < graph.offsetTop)return;
	  			
  			d3.select("#curseurPalette")
                .style("left",  x + "px")
                .style("top", y + "px");
  			d3.select("#curseurSelect")
    	            .style("width", wCurseur+"px")
    	            .style("left", x+"px")
    	            .style("top", (y-56) +"px");
                
		});

	var lstChoix = d3.select('#listeChoix')
		.on('mouseenter',function(d, i){
			noCurseur = true;
		})
		.on('mouseout',function(d, i){		  		
			noCurseur = false;
		})
		;

	drawLstChoix(curseurData)
    
    function drawLstChoix(lstData) {

		return true;
		
        var node = lstChoix.selectAll(".list-group-item")
        		.data(lstData);
          
        var newNode = node.enter()
           .append("div").attr("class", "list-group-item")
	  	   ;

        node.merge(newNode)
            .attr('id',function(d) { 
                return 'divList'+d.idG 
                })
            .style("background-color", function(d){ 
                return d.color;
                })
            .text(function(d){ 
                return d.fr;
            });
            
    }
   
	</script>
	<script src="../js/popper.min.js"></script>
	<script src="../js/bootstrap.min.js"></script>
</body>
</html>