<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script type='text/javascript' src="../js/d3.v2.js"></script>
	<script type='text/javascript' src="../js/permutation.js"></script>
	<style>	
	</style>
</head>
<body>
	<div id="chart"></div>
	<script type="text/javascript">
	
		alert(combinations({str: "EUASBT,EUASBT"}).join(", "));
		data.push([0,0,0,0,0,0]); 
		for(var j = 0; j < 6; j++)
		{
			for(var k = 0; k < 6; k++)
			{
				var n = [];
				for(var l = 0; l < 6; l++)
				{
					if(k==l && data[k][l]==0) n.push(1); else n.push(0);
				}								 
				data.push(n); 
			}	
		}
		var width = 100, height=100;
		var fill = "red";
       	var chart = d3.select("#chart");
       	var svg = chart.append("svg:svg")
            .attr("width", 800)
            .attr("height", 800)
            .append("svg:g");
		svg.selectAll(".bar")
	      .data(data)
	    .enter().append("rect")
	      .attr("class", "bar")
	      .attr("x", function(d, i) { 
		      return 10*i; 
		      })
	      .attr("width", 10)
	      .attr("y", function(d) { 
		      return 0; 
		      })
	      .attr("height", function(d, i) { 
		      return 10*i; 
		      });		
	</script>	
  </body>
</html>	