<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Streamgraph</title>
    <script src='../js/d3.v5.min.js'></script>
    <script src='../js/moment.js'></script>
    <script src='../js/streamgraph.js'></script>
    <style>
    #dataviz{
        background-color: grey;
    }
    </style>
<body>
<div id='dataviz'></div>
</body>

<script>
//
d3.select('#dataviz').style('width',window.innerWidth).style('height',window.innerHeight);
var sg = new streamgraph({
    'idCont':'dataviz'
    ,'width':window.innerWidth
    ,'height':window.innerHeight
    ,'dataUrl':"<?php echo $this->urlData; ?>"
    ,'dataType':"<?php echo $this->typeData; ?>"
    ,'orientation':'vertical'
    });
</script>    
</body>
</html>