<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Simple venn.js example</title>
<style>
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
}
ellipse{
    fill:#00c40025;opacity:0.8;stroke:#d50000;stroke-width:1.88111544;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;    
}
rect {
    opacity:1;fill:#ffffff;fill-opacity:1;stroke:#d524dd;stroke-width:1;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1    
}
.matrice{
    fill:#0b6ef45c;
}
.abs{
    fill:#f66e0025;    
}
.ord{
    fill:#f66ef45c;
}
.item{
    fill:#0b6ef45c;
}
</style>
</head>

<body>
    <div id="venn"></div>
</body>

<script src="../js/d3.v4.js"></script>
<script src="../js/vennMatrice.js"></script>
<script>
var url = '<?php echo $this->urlData;?>';
d3.json(url, function(err, data){
    matrice = [];
    var head, nbCol = data.table.tree.Tables[0].Col
    ,items = data.table.tree.Tables[0].table[0].slice
    ,mat=[];
    items.forEach(function(n, i){
        var a = ((i-1) % nbCol)-1;
        if(n.background == "header-noun"){
            if(i==0){
                n.type = 'matrice';
                head = n;
                head.abs=[];head.ord=[];head.items=[];
            }else{
                if(i <= nbCol){
                    n.type = 'abs';
                    n.abs=a;
                    head.abs.push(n.value);
                }else{
                    n.type = 'ord';
                    head.ord.push(n.value);
                    n.ord=head.ord.length-1
                }
            }
            mat.push(n);
        } else if (n.background == "noun"){
            n.type = 'item';
            n.numabs=a;
            n.numord=head.ord.length-1
            n.abs=head.abs[a];
            n.ord=head.ord[n.numord];
            head.items.push(n.value);
            mat.push(n);
        }
    });

    var chart = vennMatrice();
    d3.select("#venn")
        .datum(mat)
        .call(chart);
});



</script>
</html>
