<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Jardin des connaissances : navigation dans les cours de Gilles Deleuze</title>
	<meta name="Description" CONTENT="jardin connaissances navigation cours Gilles Deleuze"/>
	<meta name="Keywords" CONTENT="jardin connaissances navigation cours Gilles Deleuze"/>
	<meta name="Author" CONTENT="Samuel Szoniecky"/>
	
	<script type='text/javascript' src="../js/popcorn-complete.js"></script>
	<script type="text/javascript" src="../js/jquery.min.js"></script>
	<script type='text/javascript' src="../js/d3.js"></script>
	<script type='text/javascript' src="../js/d3.time.js"></script>	
	<script type='text/javascript' src="../js/d3.layout.cloud.js"></script>
	<script type='text/javascript' src="../js/selectsontexte.js"></script>
	<script type='text/javascript' src="../js/selectbar.js"></script>
	<script type='text/javascript' src="../js/tagcloud.js"></script>
	<script type='text/javascript' src="../js/deleuze.js"></script>
	
	<link rel="stylesheet" href="../css/deleuze.css" />	
	<script>

		var db = "flux_DeleuzeSpinoza";
		var idExi = '<?php echo $this->idUti; ?>';
		var mailExi = '<?php echo $this->identite;; ?>';
		
	</script>	
	
</head>
<body>
	<span>Cribles disponibles :</span>
	<select name="crible" size="1" onChange="chgcrible(this)">
		<option >Choisir un crible</option>
		<?php foreach($this->cribles as $c) : ?>
			<option value="<?php echo $c['uti_id']; ?>"><?php echo $c['login']." : ".$c['nbTag']." tag(s) - ".$c['nbDoc']." doc(s)" ; ?></option>
		<?php endforeach; ?>		
	</select>		
	<span>Interrogation directe :</span>
	<input type="text" id="rqt" />
	<input type="button" onclick="find();" value="rechercher" >
	<span class="status" >Utilisateur : <?php echo $this->identite; ?>
		<a href="../auth/login">déconnexion</a>
	</span>
	<div class="globalTC" id="gTC" >
		<div class="status" id="status_gTC"></div>
		<div id="vis_gTC"></div>
	</div>
	<div class="ref" id="gPosi" ></div>

  </body>
</html>	