<!doctype html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Editeur de formulaires sémantiques">
    <meta name="author" content="Samuel Szoniecky">

    <title>Editeur de formulaires sémantiques</title>

    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../css/w2ui-1.5.rc1.min.css" />
    <!-- Custom styles for this template -->
    <link href="../css/sticky-footer-navbar.css" rel="stylesheet">

    <script defer src="../font/font-awesome/all.min.js" ></script>

    <style>
        iframe{
            width:  100%;
        }

        /* merci à https://github.com/basilebong/bootstrap4-fullscreen-modal */
        .modal.modal-fullscreen .modal-dialog {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        max-width: none; }

        .modal.modal-fullscreen .modal-content {
        height: auto;
        min-height: 100%;
        border-radius: 0;
        border: none; }

        .links line {
        stroke: #999;
        stroke-opacity: 0.6;
        }

        .nodes circle {
        stroke: #fff;
        stroke-width: 1.5px;
        }

        text {
        font-family: sans-serif;
        font-size: 10px;
        }

    </style>
</head>

<body>

    <header>
        <!-- Fixed navbar -->
        <nav id="mainNav" class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Editeur de formulaires sémantiques</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                
                <ul class="navbar-nav">
                    <form class="form-inline mt-2 mt-md-0">
                        <button id="btnSauver" class="btn btn-outline-primary " type="button">Enregistrer</button>
                        <button id="btnExport" class="btn btn-outline-primary " type="button">Exporter</button>
                        <button id="btnImport" class="btn btn-outline-primary " type="button">Importer</button>
                    </form>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="nbddFormDispo" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Formulaires disponibles
                        </a>
                        <div id="mnuFormDispo" class="dropdown-menu" aria-labelledby="nbddFormDispo">
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">

        <div class="row">
            <div class="col-12">

                <ul class="nav nav-tabs" id="tabForm" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="formParam-tab" data-toggle="tab" href="#formParam" role="tab"
                            aria-controls="formParam" aria-selected="true">Paramètres</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="formTest-tab" data-toggle="tab" href="#formTest" role="tab"
                            aria-controls="formTest" aria-selected="true">Tests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="formDiffusion-tab" data-toggle="tab" href="#formDiffusion" role="tab"
                            aria-controls="formDiffusion" aria-selected="true">Diffusions</a>
                    </li>
                </ul>
                <div class="tab-content" id="tabFormContent">
                    <div class="tab-pane fade show active" id="formParam" role="tabpanel" aria-labelledby="formParam-tab">
                        <div class="row">
                            <div class="col-12">
                                <div id="gridForms" style="width: 100%; height: 200px;"></div>
<!--
                                <form id='paramsForm' role="form">
                                    <div class="row">
                                        <div class="col">

                                        <div class="form-row">
                                            <div class="form-group col-md-2">
                                               <label for="iptIdForm">ID</label>
                                                <input type="text" type="text" readonly class="form-control-plaintext" id="iptIdForm" aria-describedby="hlpIdForm">
                                             </div>
                                            <div class="form-group col-md-10">
                                                <label for="iptForm">Nom du formulaire</label>
                                                <input type="text" class="form-control" id="iptForm" aria-describedby="hlpQ"
                                                    placeholder="Saisissez le nom">
                                                <small id="hlpQ" class="form-text text-muted">Privilégier un nom court</small>
                                            </div>
                                        </div>
                                            <div class="form-group form-check">
                                                <input type="checkbox" checked='true' class="form-check-input" id="chkGeo">
                                                <label class="form-check-label" for="chkGeo">Prendre en compte la
                                                    position géographique</label>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <label for="iptFormIeml">code IEML du formulaire</label>
                                                <input type="text" class="form-control" id="iptFormIeml"
                                                    aria-describedby="hlpQIeml" placeholder="code IEML">
                                                <small id="hlpQIeml" class="form-text text-muted">Saississez le code
                                                    IEML correspond au formulaire</small>
                                            </div>
                                            <div class="form-group form-check">
                                                <input type="checkbox" checked='true' class="form-check-input" id="chkTime">
                                                <label class="form-check-label" for="chkTime">Prendre en compte le
                                                    temps de réponse</label>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group form-check">
                                                <input type="checkbox" checked='true' class="form-check-input" id="chkBDD">
                                                <label class="form-check-label" for="chkBDD">Enregistrer les réponses dans la BDD</label>
                                            </div>
                                            <div class="form-group">
                                                <label for="iptBddID">Nom de la BDD</label>
                                                <input type="text" class="form-control" id="iptBddID"
                                                    aria-describedby="hlpBddID" value="flux_formsem" readonly>
                                                <small id="hlpBddID" class="form-text text-muted">Contacter l'administrateur pour changer cette valeur</small>
                                            </div>


                                        </div>

                                    </div>
                                </form>
    -->
                                <div id="gridQuestions" style="width: 100%; height: 200px;"></div>
                                <div id="gridPropositions" style="width: 100%; height: 200px;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="formTest" role="tabpanel" aria-labelledby="formTest-tab">
                        <div class="row">
                            <div class="col-4" id="formTest-form">
                                <nav class="navbar navbar-light bg-light">
                                    <form class="form-inline">
                                        <button id="btnGenForm" class="btn btn-sm btn-outline-success" type="button">Générer
                                            un formulaire</button>
                                        <button id="btnClearRep" class="btn btn-sm btn-outline-danger" type="button">Supprimer
                                            les réponses</button>
                                    </form>
                                </nav>
                            </div>
                            <div class="col-8" id="formTest-result">
                                <nav id='navViz' class="navbar navbar-light bg-light">
                                    <form class="form-inline">
                                        <button id="btnVizRepo" class="btn btn-sm btn-outline-success" type="button">Visualiser
                                            les réponses</button>
                                    </form>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="formDiffusion" role="tabpanel" aria-labelledby="formDiffusion-tab">
                        <div class="row">
                            <div class="col-6">
                                <nav class="navbar navbar-light bg-light">
                                    <form class="form-inline">
                                        <button id="btnGenIframe" class="btn btn-sm btn-outline-success" type="button">Générer
                                            un iframe</button>
                                        <button id="btnGenPWA" class="btn btn-sm btn-outline-success" type="button">Générer
                                            une PWA</button>
                                    </form>
                                </nav>
                            </div>
                            <div class="col-6" id="formDiffusion-result">
                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>

    </main>

    <footer class="footer">
        <div class="container">
            <i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-zero"></i> Samuel Szoniecky <img
                src="../svg/logo-paragraphe.svg" alt="logo-paragraphe" height="auto" width="100px" />
        </div>
    </footer>


    <!-- Modal pour le choix des concepts dans les matrices IEML-->
    <div class="modal fade modal-fullscreen" id="modalIemlMatrice" tabindex="-1" role="dialog" aria-labelledby="modalIemlMatriceLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalIemlMatriceLabel">Choississez les concepts dans les matrices IEML</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nbAddIEML"
                            aria-controls="nbAddIEML" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="nbAddIEML">
                            <ul class="navbar-nav">
                                <!--
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="nbddMatricesIEML" role="button"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Matrices IEML
                                    </a>
                                    <div id="mnuMatrices" class="dropdown-menu" aria-labelledby="nbddMatricesIEML">
                                    </div>
                                </li>
                                -->
                                <form class="form-inline">
                                    <div class="w2ui-field" >
                                        <label class="text-white bg-dark" >Matrices IEML :</label>
                                        <div > <input  id="enum-matriceIeml"> </div>
                                    </div>            
                                    <div class="w2ui-field" >
                                        <label class="text-white bg-dark" >Dico IEML :</label>
                                        <div > <input  id="enum-itemIeml"> </div>
                                    </div>            
                                    <div id="btnCptLigne" class="btn-group btn-group-toggle" data-toggle="buttons">
                                        <label class="btn btn-sm btn-outline-success active">
                                            <input type="radio" name="options" id="cptLigne" autocomplete="off" checked>
                                            Une réponse par concept
                                        </label>
                                        <label class="btn  btn-sm btn-outline-success">
                                            <input type="radio" name="options" id="cptCumul" autocomplete="off">
                                            Cumuler les concepts
                                        </label>
                                    </div>
                                </form>
                            </ul>
                        </div>
                    </nav>
                    <div class="row">
                        <div class="col-12">
                            <iframe id="ifMatriceIEML" title="Matrice IEML" src=""></iframe>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Fenêtre modale pour le choix d'un fichier -->
    <div class="modal fade" id="modGetFic" tabindex="-1" role="dialog" aria-labelledby="modGetFicLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modGetFicLabel">Importer les paramètres du formulaire<span class="modalTitle"
                            id="modGetFicInt"></span></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="w2ui-field">
                        <div style="margin-left: 0px;"> <input style="width:100%;" id="fileImport"> </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    <button id="btnValidImport" type="button" class="btn btn-primary">Valider</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        var urlIeml = "<?php echo $this->urlIeml;?>",
            urlDico = "<?php echo $this->urlDico;?>";
    </script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="../js/d3.v4.js"></script>
    <script type="text/javascript" src="../js/jquery.min.js"></script>
    <script type="text/javascript" src="../js/popper.min.js"></script>
    <script type="text/javascript" src="../js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../js/bootstrap-treeview.js"></script>
    <script type="text/javascript" src="../js/w2ui.min.js"></script>
    <script type="text/javascript" src="../js/ieml.js"></script>
    <script type="text/javascript" src="../js/iemlForce.js"></script>
    <script type="text/javascript" src="../js/geo.js"></script>
    <script type="text/javascript" src="../js/d3-hexbin0.2.2.min.js"></script>
    <script type="text/javascript" src="../js/d3-force.v2.min.js"></script>
    <script type="text/javascript" src="../js/ice/editeur.js"></script>

</body>

</html>