<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>IEML concept map</title>
    <script src="../font/font-awesome/all.min.js"></script>
<style>
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    background-color: black;
    width: 100%;
    height: 100%
}
ellipse{
    fill:#00c40025;opacity:0.8;stroke:#d50000;stroke-width:1.88111544;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;    
}
rect {
    opacity:1;fill:#ffffff;fill-opacity:1;stroke:white;stroke-width:1;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1    
}
text {
    font-style:normal;font-weight:normal;font-size:3.17499995px;line-height:0%;font-family:sans-serif;text-align:center;letter-spacing:0px;word-spacing:0px;text-anchor:middle;fill:white;fill-opacity:1;stroke:none;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;
}
.matrice{
    fill:#0b6ef45c;
}
.abs{
    fill:#f66e0025;    
}
.ord{
    fill:#f66ef45c;
}
.item{
    fill:#0b6ef45c;
}
</style>
</head>

<body>
</body>

<script src="../js/d3.v4.js"></script>
<script src="../js/vennMatrice.js"></script>
<script src="../js/ieml.js"></script>
<script>
var urlData = "<?php echo $this->urlData;?>",
    urlDico = "<?php echo $this->urlDico;?>",
    arrDico, iemlMatrice;
//récupération des data du dictionnaire
d3.json(urlDico, function(err, data){
    arrDico = data;
    //récupération des data du concept
    d3.json(urlData, function(err, data){
        makeMatrice(getIemlItems(data));
    });
});

function makeMatrice(mat){

    //construction de la matrice Venn
    var iemlMatrice = vennMatrice();
    d3.select("body")
        .datum(mat)
        .call(iemlMatrice);

}

</script>
</html>
