<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8" />
		<title>ExCode</title>
		<meta name="description" content=" " />
		<meta name="keywords" content=" " />
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<link rel="icon" type="image/png" href="img/excode/icon.png" />
		<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
		<link href="css/excode/reset.css" rel="stylesheet" type="text/css"/>
		<link href="css/excode/style.css" rel="stylesheet" type="text/css"/>
		<link href="css/excode/jeu.css" rel="stylesheet" type="text/css"/>
		
	    	<script type="text/javascript" src="js/d3.v3.js"></script>
		<script type="text/javascript" src="js/d3.hexbin.min.js"></script>
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>  				
	</head>
	<body>
		<header>
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<img id="logo" src="img/excode/logo.png" title="iks-ray" alt="logo de iks-ray"/>
						<img id="logo-mini" src="img/excode/logo-mini.png" title="iks-ray" alt="logo de iks-ray"/>
						<img id="btn-nav" src="img/excode/bstrap.png" alt="menu"/>
						<img id="btn-equipe-phone" class="icone-equipe-joueur" src="img/excode/equipe.png" alt="equipe"/>
					</div>
				</div>
			</div>
		</header>
		
		<div id="content">
			<section class="container">
					<div class="row">
						<div class="col-md-12 centre">
							<a href="<?php echo $this->urlConnect; ?>" class="btn btn-info" role="button">Connexion</a>
						</div>
					</div>
			</section>
		</div>
	</body>	
</html>